import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, CalendarDays, CheckCircle2, ClipboardCheck, FileText, MapPin, PackageCheck, Truck, Upload, Weight } from "lucide-react";
import { requireActor, canPlan, canWorkService } from "@/lib/auth";
import { db } from "@/lib/db";
import { getService, PilotError } from "@/lib/pilot";
import { addEvidenceAction, assignServiceAction, cancelServiceAction, createDriverForServiceAction, finishServiceAction, saveChecklistAction, startServiceAction } from "@/app/actions";
import { Badge, Breadcrumb, chileDate, Notice } from "@/components/UI";
import { SubmitButton } from "@/components/Transition";

function localInput(value: Date | string | null) {
  if (!value) return "";
  const parts = new Intl.DateTimeFormat("sv-SE", { timeZone: "America/Santiago", year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit", hourCycle: "h23" }).format(new Date(value));
  return parts.replace(" ", "T");
}

export default async function ServiceDetail({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ error?: string; ok?: string }> }) {
  const actor = await requireActor();
  const { id } = await params;
  let service;
  try { service = await getService(actor, id); }
  catch (error) { if (error instanceof PilotError) notFound(); throw error; }
  const [timeline, evidence, checks, assets, ramps, drivers, containerMoves, wasteRecord, certificate] = await Promise.all([
    db.query<{ id: string; description: string; kind: string; created_at: Date; actor_name: string }>(
      `SELECT e.id,e.description,e.kind,e.created_at,u.name AS actor_name FROM service_events e
       LEFT JOIN users u ON u.id=e.actor_id WHERE e.service_id=$1 ORDER BY e.created_at DESC,e.id DESC`, [id],
    ),
    db.query<{ id: string; description: string; original_filename: string | null; created_at: Date }>(
      "SELECT id,description,original_filename,created_at FROM service_evidence WHERE service_id=$1 ORDER BY created_at DESC", [id],
    ),
    db.query<{ vehicle_ok: boolean; documents_ok: boolean; containment_ok: boolean; ppe_ok: boolean; comment: string | null; completed_at: Date }>(
      "SELECT vehicle_ok,documents_ok,containment_ok,ppe_ok,comment,completed_at FROM service_checklists WHERE service_id=$1", [id],
    ),
    canPlan(actor) ? db.query<{ id: string; label: string; code: string }>("SELECT id,label,code FROM assets WHERE available=true AND deleted_at IS NULL AND kind='camion' ORDER BY label") : Promise.resolve([]),
    canPlan(actor) ? db.query<{ id: string; label: string; code: string }>("SELECT id,label,code FROM assets WHERE available=true AND deleted_at IS NULL AND kind='rampa' ORDER BY label") : Promise.resolve([]),
    canPlan(actor) ? db.query<{ id: string; name: string }>("SELECT id,name FROM users WHERE role='conductor' AND active=true ORDER BY name") : Promise.resolve([]),
    db.query<{id:string;code:string;kind:string;previous_location:string|null;next_location:string;created_at:Date}>(`SELECT m.id,c.code,m.kind,m.previous_location,m.next_location,m.created_at
      FROM container_movements m JOIN containers c ON c.id=m.container_id WHERE m.service_id=$1 ORDER BY m.created_at DESC`,[id]),
    canPlan(actor) ? db.query<{id:string;status:string}>("SELECT id,status FROM waste_records WHERE service_id=$1",[id]) : Promise.resolve([]),
    actor.role!=="conductor"?db.query<{id:string}>("SELECT id FROM service_certificates WHERE service_id=$1 AND status='vigente'",[id]):Promise.resolve([]),
  ]);
  const checklist = checks[0];
  const paramsQuery = await searchParams;
  const canWork = canWorkService(actor, service);
  const canAssign = canPlan(actor) && ["solicitada", "programada"].includes(service.status);
  const certificateReady=["revisado","declarado"].includes(wasteRecord[0]?.status??"");
  return <>
    <Breadcrumb label={`RER-${String(service.folio).padStart(5,"0")}`}/>
    <div className="page-title-row detail-heading"><div><div className="eyebrow">SOLICITUD DE SERVICIO</div><h1>RER-{String(service.folio).padStart(5,"0")}</h1><p className="page-intro">{service.client_name} · {service.site_name}</p></div><Badge status={service.status}/></div>
    <Notice error={paramsQuery.error} ok={paramsQuery.ok}/>
    <div className="detail-grid">
      <div className="detail-main">
        <section className="section-card"><div className="section-heading"><div><div className="eyebrow">DATOS PRINCIPALES</div><h2>Servicio solicitado</h2></div><span className={`priority priority-${service.priority}`}>{service.priority === "critica" ? "Prioridad crítica" : service.priority === "alta" ? "Prioridad alta" : "Prioridad normal"}</span></div>
          <div className="facts-grid"><div className="fact"><span>Tipo de servicio</span><strong className="capitalize">{service.service_type}</strong></div><div className="fact"><span>Residuo o material</span><strong>{service.waste_type}</strong></div><div className="fact"><span>Cantidad estimada</span><strong>{service.estimated_kg ? `${Number(service.estimated_kg).toLocaleString("es-CL")} kg` : "Sin estimación"}</strong></div><div className="fact"><span>Registrada</span><strong>{chileDate(service.created_at)}</strong></div><div className="fact"><span><MapPin size={15}/> Origen</span><strong>{service.origin}</strong></div><div className="fact"><span><MapPin size={15}/> Destino</span><strong>{service.destination}</strong></div></div>
          {service.notes && <div className="note-block"><span>Observaciones</span><p>{service.notes}</p></div>}
        </section>
        <section className="section-card"><div className="section-heading"><div><div className="eyebrow">DESPACHO</div><h2><Truck size={19}/> Planificación y recursos</h2></div></div>
          {service.scheduled_for && <div className="assigned-summary"><div><CalendarDays size={19}/><span><small>Fecha y hora</small><strong>{chileDate(service.scheduled_for)}</strong></span></div><div><Truck size={19}/><span><small>Camión / conductor</small><strong>{service.asset_label ?? "—"} · {service.driver_name ?? "—"}</strong></span></div>{service.ramp_label && <div><Truck size={19}/><span><small>Rampa asignada</small><strong>{service.ramp_label}</strong></span></div>}{service.guide_number && <div><FileText size={19}/><span><small>Guía</small><strong>{service.guide_number}</strong></span></div>}</div>}
          {service.scheduled_for && <Link className="order-link" href={`/solicitudes/${service.id}/orden`}><FileText size={16}/> Ver orden de servicio para imprimir →</Link>}
          {canAssign && (!assets.length || !drivers.length) && <div className="resource-alert"><strong>Faltan recursos para programar este servicio.</strong><span>{!assets.length ? "Registre un camión en Maestros. " : ""}{!drivers.length ? actor.role === "admin" ? "Cree un conductor aquí mismo o prepare los datos de demostración." : "Solicite a administración que registre un conductor." : ""}</span>{!assets.length && <Link href="/maestros">Ir a Maestros →</Link>}{!drivers.length && actor.role === "admin" && <form action={createDriverForServiceAction} className="form-stack compact inline-driver"><input type="hidden" name="id" value={service.id}/><div className="two-fields"><label>Nombre del conductor<input name="name" required maxLength={120} placeholder="Nombre y apellido"/></label><label>Correo del conductor<input name="email" type="email" required placeholder="conductor@empresa.cl"/></label></div><label>Contraseña inicial (mínimo 12 caracteres)<input name="password" type="password" minLength={12} maxLength={128} autoComplete="new-password" required/></label><SubmitButton className="button button-outline">Crear conductor y volver al despacho</SubmitButton></form>}</div>}
          {canAssign && <form action={assignServiceAction} className="form-grid detail-form"><input type="hidden" name="id" value={service.id}/><label>Fecha y hora (Chile)<input type="datetime-local" name="scheduled_for" defaultValue={localInput(service.scheduled_for)} required/></label><label>Camión<select name="asset_id" defaultValue={service.assigned_asset_id ?? ""} required><option value="">Seleccione un camión</option>{assets.map((asset) => <option value={asset.id} key={asset.id}>{asset.code} · {asset.label}</option>)}</select></label><label>Conductor<select name="driver_id" defaultValue={service.driver_id ?? ""} required><option value="">Seleccione un conductor</option>{drivers.map((driver) => <option value={driver.id} key={driver.id}>{driver.name}</option>)}</select></label><label>Rampa (si corresponde)<select name="ramp_asset_id" defaultValue={service.ramp_asset_id ?? ""}><option value="">Sin rampa</option>{ramps.map((ramp) => <option value={ramp.id} key={ramp.id}>{ramp.code} · {ramp.label}</option>)}</select></label><label>Número de guía (opcional)<input name="guide_number" defaultValue={service.guide_number ?? ""} maxLength={50}/></label><div className="field-full form-footer"><SubmitButton className="button button-primary" disabled={!assets.length || !drivers.length}>{service.status === "programada" ? "Actualizar planificación" : "Programar servicio"}</SubmitButton></div></form>}
          {canAssign && <details className="cancel-control"><summary>Cancelar este servicio</summary><form action={cancelServiceAction} className="form-stack compact"><input type="hidden" name="id" value={service.id}/><label>Motivo de la cancelación<textarea name="reason" rows={2} minLength={5} maxLength={500} required placeholder="Explique por qué no continuará el servicio"/></label><SubmitButton className="button button-outline">Confirmar cancelación</SubmitButton></form></details>}
          {service.status === "cancelada" && <p className="cancelled-note">Este servicio fue cancelado. El motivo y responsable quedaron registrados en el historial.</p>}
          {!service.scheduled_for && !canAssign && <p className="muted">Pendiente de planificación por el equipo de operaciones.</p>}
        </section>
        {canWork && service.status === "programada" && <section className="section-card"><div className="section-heading"><div><div className="eyebrow">CONTROL PREVIO</div><h2><ClipboardCheck size={19}/> Checklist antes de salir</h2></div></div><form action={saveChecklistAction} className="form-stack"><input type="hidden" name="id" value={service.id}/><div className="check-grid"><label className="check-row"><input type="checkbox" name="vehicle_ok" defaultChecked={checklist?.vehicle_ok}/><span>Vehículo inspeccionado</span></label><label className="check-row"><input type="checkbox" name="documents_ok" defaultChecked={checklist?.documents_ok}/><span>Documentos y guía revisados</span></label><label className="check-row"><input type="checkbox" name="containment_ok" defaultChecked={checklist?.containment_ok}/><span>Carga y contención verificadas</span></label><label className="check-row"><input type="checkbox" name="ppe_ok" defaultChecked={checklist?.ppe_ok}/><span>Elementos de protección disponibles</span></label></div><label>Observaciones<textarea name="comment" rows={3} defaultValue={checklist?.comment ?? ""} placeholder="Anote hallazgos o condiciones antes de salir"/></label><SubmitButton className="button button-outline">Guardar checklist</SubmitButton></form>
          {checklist && [checklist.vehicle_ok, checklist.documents_ok, checklist.containment_ok, checklist.ppe_ok].every(Boolean) && <form action={startServiceAction} className="next-action"><input type="hidden" name="id" value={service.id}/><span><CheckCircle2 size={18}/> Verificaciones completas</span><SubmitButton className="button button-primary">Iniciar ruta</SubmitButton></form>}</section>}
        {canWork && ["programada", "en_ruta"].includes(service.status) && <section className="section-card"><div className="section-heading"><div><div className="eyebrow">RESPALDO</div><h2><Upload size={19}/> Evidencia del servicio</h2></div></div><p className="helper-text">Agregue fotografías o documentos (PDF, JPG, PNG o WebP; máximo {process.env.VERCEL?4:5} MB por archivo).</p><form action={addEvidenceAction} className="form-stack"><input type="hidden" name="id" value={service.id}/><label>Descripción<input name="description" maxLength={500} required placeholder="Ej. Guía firmada en punto de retiro"/></label><label>Archivo<input name="file" type="file" accept=".pdf,.jpg,.jpeg,.png,.webp,application/pdf,image/jpeg,image/png,image/webp" required/></label><SubmitButton className="button button-outline">Guardar evidencia</SubmitButton></form></section>}
        {canWork && service.status === "en_ruta" && <section className="section-card"><div className="section-heading"><div><div className="eyebrow">CIERRE</div><h2><Weight size={19}/> Pesaje y finalización</h2></div></div><p className="helper-text">Para completar el servicio, registre el pesaje y adjunte al menos un archivo de evidencia.</p><form action={finishServiceAction} className="form-grid detail-form"><input type="hidden" name="id" value={service.id}/><label>Peso bruto (kg)<input name="gross_kg" type="number" min="0.01" step="0.01" required/></label><label>Tara (kg)<input name="tare_kg" type="number" min="0" step="0.01" required/></label><label className="field-full">Número de guía<input name="guide_number" defaultValue={service.guide_number ?? ""} maxLength={50}/></label><div className="field-full form-footer"><SubmitButton className="button button-primary">Cerrar servicio</SubmitButton></div></form></section>}
        {service.status === "completada" && <section className="section-card completion-card"><div className="section-heading"><div><div className="eyebrow">CIERRE REGISTRADO</div><h2><PackageCheck size={20}/> Servicio completado</h2></div></div><div className="facts-grid"><div className="fact"><span>Peso bruto</span><strong>{Number(service.gross_kg).toLocaleString("es-CL")} kg</strong></div><div className="fact"><span>Tara</span><strong>{Number(service.tare_kg).toLocaleString("es-CL")} kg</strong></div><div className="fact"><span>Peso neto</span><strong>{(Number(service.gross_kg) - Number(service.tare_kg)).toLocaleString("es-CL")} kg</strong></div></div>{actor.role==="admin"&&<Link className="button button-outline" href={`/finanzas/${id}`}>Valorizar y registrar cobros →</Link>}{canPlan(actor)&&<Link className="button button-outline" href={wasteRecord[0]?`/cumplimiento/${wasteRecord[0].id}`:`/cumplimiento?service_id=${id}`}>{wasteRecord[0]?`Registro ambiental · ${wasteRecord[0].status}`:"Preparar ficha ambiental para el certificado"} →</Link>}{certificate[0]&&<Link className="button button-outline" href={`/api/certificados/${certificate[0].id}/pdf`}>Descargar certificado PDF + QR</Link>}{actor.role==="admin"&&!certificate[0]&&certificateReady&&<Link className="button button-outline" href="/certificados">Emitir certificado →</Link>}{actor.role==="admin"&&!certificate[0]&&!certificateReady&&<p className="certificate-step-hint">Para emitir el certificado, prepare y revise primero la ficha ambiental de este servicio.</p>}</section>}
      </div>
      <aside className="detail-side">
        <section className="section-card side-card"><div className="eyebrow">ESTADO DEL SERVICIO</div><div className="progress-list">{["solicitada", "programada", "en_ruta", "completada"].map((state, index, all) => <div className={`progress-step ${all.indexOf(service.status) >= index ? "done" : ""}`} key={state}><span className="progress-number">{index + 1}</span><span>{state === "en_ruta" ? "En ruta" : state.charAt(0).toUpperCase() + state.slice(1)}</span></div>)}</div></section>
        <section className="section-card side-card"><div className="section-heading"><div><div className="eyebrow">ARCHIVOS</div><h2>Evidencias</h2></div><span className="count-pill">{evidence.length}</span></div>{evidence.length ? <ul className="evidence-list">{evidence.map((item) => <li key={item.id}><FileText size={17}/><div><strong>{item.description}</strong>{item.original_filename && <Link href={`/api/evidencia/${item.id}`}>{item.original_filename}</Link>}<small>{chileDate(item.created_at)}</small></div></li>)}</ul> : <p className="muted">Sin archivos adjuntos.</p>}</section>
        {containerMoves.length>0&&<section className="section-card side-card"><div className="eyebrow">CONTENEDORES</div><h2>Movimientos asociados</h2><ol className="timeline">{containerMoves.map((move)=><li key={move.id}><span className="timeline-marker"/><strong>{move.code} · {move.kind.replaceAll("_"," ")}</strong><small>{move.previous_location?`${move.previous_location} → `:""}{move.next_location} · {chileDate(move.created_at)}</small></li>)}</ol></section>}
        <section className="section-card side-card"><div className="eyebrow">TRAZABILIDAD</div><h2>Historial</h2><ol className="timeline">{timeline.map((item) => <li key={item.id}><span className="timeline-marker"/><strong>{item.description}</strong><small>{item.actor_name ?? "Sistema"} · {chileDate(item.created_at)}</small></li>)}</ol></section>
        <Link className="back-link" href="/solicitudes"><ArrowLeft size={16}/> Volver a solicitudes</Link>
      </aside>
    </div>
  </>;
}
