import { redirect } from "next/navigation";
import { ShieldCheck, UserRound, CalendarClock, MapPin } from "lucide-react";
import { canManage, requireActor } from "@/lib/auth";
import { listPersonnel } from "@/lib/personnel";
import { createRequirementAction, disableRequirementAction, recordCredentialAction, reviewCredentialAction, saveWorkerProfileAction } from "@/app/personnel-actions";
import { Notice, chileDate } from "@/components/UI";
import { SubmitButton } from "@/components/Transition";

function iso(value:Date|string){return value instanceof Date?value.toISOString().slice(0,10):String(value).slice(0,10);}
const formatDay=(value:Date|string)=>chileDate(`${iso(value)}T12:00:00Z`,false);
export default async function Personnel({searchParams}:{searchParams:Promise<{error?:string;ok?:string}>}) {
  const actor=await requireActor();
  if(!canManage(actor)) redirect("/");
  const [{workers,clients,sites,requirements,credentials},query]=await Promise.all([listPersonnel(actor),searchParams]);
  const today=new Intl.DateTimeFormat("sv-SE",{timeZone:"America/Santiago",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
  const activeDrivers=workers.filter((worker)=>worker.role==="conductor");
  const pending=credentials.filter((credential)=>credential.state==="pendiente").length;
  const expired=credentials.filter((credential)=>credential.state==="verificada"&&iso(credential.expires_on)<today).length;
  const coverage=sites.flatMap((site)=>{
    const required=requirements.filter((r)=>r.client_id===site.client_id && (!r.site_id || r.site_id===site.id));
    if(!required.length) return [];
    return activeDrivers.map((worker)=>({site,worker,required,missing:required.filter((requirement)=>!credentials.some((credential)=>credential.user_id===worker.id && credential.requirement_id===requirement.id && credential.state==="verificada" && iso(credential.issued_on)<=today && iso(credential.expires_on)>=today))}));
  });
  return <>
    <div className="page-title-row"><div><div className="eyebrow">HABILITACIÓN POR FAENA</div><h1>Personal y acreditaciones</h1><p className="page-intro">Registre requisitos, fechas de vigencia y verificaciones antes de asignar conductores.</p></div><span className="title-icon"><ShieldCheck size={23}/></span></div>
    <Notice error={query.error} ok={query.ok}/>
    <div className="supply-summary"><div><strong>{activeDrivers.length}</strong><span>Conductores activos</span></div><div><strong>{pending}</strong><span>Documentos por revisar</span></div><div><strong>{expired}</strong><span>Verificados y vencidos</span></div><div><strong>{requirements.length}</strong><span>Requisitos por cliente o faena</span></div></div>
    <section className="section-card"><div className="section-heading"><div><div className="eyebrow">DESPACHO</div><h2><MapPin size={19}/> Habilitación por conductor y faena</h2></div><span className="count-pill">{coverage.length}</span></div>
      <p className="helper-text">Un conductor con requisitos pendientes, vencidos o rechazados no puede ser programado en esa faena. Cuando una faena no tiene requisitos configurados, la planificación sigue disponible.</p>
      {coverage.length?<div className="table-wrap"><table className="data-table"><thead><tr><th>Conductor</th><th>Cliente / faena</th><th>Estado</th><th>Requisitos pendientes</th></tr></thead><tbody>{coverage.slice(0,150).map(({site,worker,missing})=><tr key={`${worker.id}:${site.id}`}><td><strong>{worker.name}</strong></td><td>{site.client_name}<span className="table-sub">{site.name}</span></td><td>{missing.length?<span className="inventory-low">Faltan {missing.length}</span>:<span className="inventory-good">Habilitado</span>}</td><td>{missing.map((requirement)=>requirement.name).join(" · ")||"—"}</td></tr>)}</tbody></table></div>:<p className="muted">Al definir requisitos para una faena aparecerá aquí su matriz de habilitación.</p>}{coverage.length>150&&<p className="helper-text">Vista inicial: 150 combinaciones. El bloqueo de despacho se verifica para todas las faenas.</p>}
    </section>
    <div className="supply-columns">
      <section className="section-card"><div className="section-heading"><div><div className="eyebrow">FICHA DEL TRABAJADOR</div><h2><UserRound size={19}/> Datos de operación</h2></div></div><form action={saveWorkerProfileAction} className="form-stack compact"><label>Trabajador<select name="user_id" defaultValue="" required><option value="">Seleccione</option>{workers.map((worker)=><option key={worker.id} value={worker.id}>{worker.name} · {worker.role}</option>)}</select></label><div className="two-fields"><label>Identificación<input name="national_id" maxLength={20}/></label><label>Cargo<input name="position" maxLength={120}/></label></div><div className="two-fields"><label>Turno<input name="shift" maxLength={80}/></label><label>Teléfono<input name="phone" maxLength={40}/></label></div><SubmitButton className="button button-outline" disabled={!workers.length}>Guardar ficha</SubmitButton></form><ul className="record-list">{workers.map((worker)=><li key={worker.id}><strong>{worker.name}</strong><small>{worker.position||worker.role} · {worker.shift||"Sin turno"}</small></li>)}</ul></section>
      <section className="section-card"><div className="section-heading"><div><div className="eyebrow">REGLAS POR CLIENTE</div><h2><ShieldCheck size={19}/> Agregar requisito</h2></div></div><form action={createRequirementAction} className="form-stack compact"><label>Cliente<select name="client_id" defaultValue="" required><option value="">Seleccione</option>{clients.map((client)=><option key={client.id} value={client.id}>{client.name}</option>)}</select></label><label>Faena (opcional: aplica a todas las faenas del cliente)<select name="site_id" defaultValue=""><option value="">Todas las faenas del cliente</option>{sites.map((site)=><option key={site.id} value={site.id}>{site.client_name} · {site.name}</option>)}</select></label><label>Documento o habilitación requerida<input name="name" minLength={3} maxLength={150} required placeholder="Licencia clase A5, examen, inducción…"/></label><div className="two-fields"><label>Tipo<select name="kind" defaultValue="licencia"><option value="licencia">Licencia</option><option value="curso">Curso</option><option value="examen">Examen</option><option value="acreditacion">Acreditación</option><option value="otro">Otro</option></select></label><label>Advertir con días de anticipación<input name="warning_days" type="number" min="0" max="365" defaultValue="30" required/></label></div><SubmitButton className="button button-outline" disabled={!clients.length}>Agregar requisito</SubmitButton></form>
        <ul className="record-list">{requirements.map((requirement)=><li key={requirement.id}><div><strong>{requirement.name}</strong><small>{requirement.client_name} · {requirement.site_name??"Todas las faenas"}</small></div>{actor.role==="admin"&&<details className="small-action"><summary>Desactivar</summary><form action={disableRequirementAction} className="form-stack compact"><input type="hidden" name="requirement_id" value={requirement.id}/><input name="reason" minLength={5} maxLength={500} required placeholder="Motivo"/><SubmitButton className="button button-outline">Guardar</SubmitButton></form></details>}</li>)}</ul></section>
      <section className="section-card"><div className="section-heading"><div><div className="eyebrow">VIGENCIAS</div><h2><CalendarClock size={19}/> Registrar documento</h2></div></div><p className="helper-text">La referencia identifica el documento o respaldo. Un administrador debe verificar sus fechas antes de habilitar al conductor.</p><form action={recordCredentialAction} className="form-stack compact"><label>Conductor<select name="user_id" defaultValue="" required><option value="">Seleccione</option>{activeDrivers.map((worker)=><option key={worker.id} value={worker.id}>{worker.name}</option>)}</select></label><label>Requisito<select name="requirement_id" defaultValue="" required><option value="">Seleccione</option>{requirements.map((requirement)=><option key={requirement.id} value={requirement.id}>{requirement.name} · {requirement.client_name}{requirement.site_name?` / ${requirement.site_name}`:""}</option>)}</select></label><label>Folio o referencia<input name="reference" required minLength={2} maxLength={160}/></label><div className="two-fields"><label>Fecha de emisión<input name="issued_on" type="date" required/></label><label>Vencimiento<input name="expires_on" type="date" required/></label></div><SubmitButton className="button button-outline" disabled={!activeDrivers.length||!requirements.length}>Registrar para revisión</SubmitButton></form></section>
      <section className="section-card"><div className="section-heading"><div><div className="eyebrow">REVISIÓN</div><h2>Documentos y decisiones</h2></div><span className="count-pill">{credentials.length}</span></div>{credentials.length?<ul className="personnel-records">{credentials.map((credential)=>{
        const requirement=requirements.find((r)=>r.id===credential.requirement_id);
        const expires=iso(credential.expires_on);
        const warning=credential.state==="verificada" && expires>=today && Number((new Date(`${expires}T12:00:00Z`).getTime()-new Date(`${today}T12:00:00Z`).getTime())/86400000)<=Number(requirement?.warning_days??30);
        return <li key={credential.id}><strong>{credential.worker_name} · {credential.requirement_name}</strong><small>{credential.client_name} / {credential.site_name??"Todas las faenas"} · ref. {credential.reference}</small><small>Emisión {formatDay(credential.issued_on)} · vence {formatDay(credential.expires_on)}</small><span className={credential.state==="pendiente"||expires<today||warning?"inventory-low":"inventory-good"}>{credential.state==="verificada"&&expires<today?"Vencida":warning?"Próxima a vencer":credential.state}</span>{credential.review_note&&<small>Revisión: {credential.review_note}</small>}{actor.role==="admin"&&credential.state==="pendiente"&&<div className="credential-actions"><form action={reviewCredentialAction}><input type="hidden" name="credential_id" value={credential.id}/><input type="hidden" name="decision" value="verificada"/><SubmitButton className="button button-outline">Verificar</SubmitButton></form><form action={reviewCredentialAction} className="credential-review"><input type="hidden" name="credential_id" value={credential.id}/><input type="hidden" name="decision" value="rechazada"/><input name="reason" required minLength={5} maxLength={500} placeholder="Motivo rechazo"/><SubmitButton className="button button-outline">Rechazar</SubmitButton></form></div>}{actor.role==="admin"&&credential.state==="verificada"&&<details className="small-action"><summary>Revocar</summary><form action={reviewCredentialAction} className="form-stack compact"><input type="hidden" name="credential_id" value={credential.id}/><input type="hidden" name="decision" value="revocada"/><input name="reason" required minLength={5} maxLength={500} placeholder="Motivo"/><SubmitButton className="button button-outline">Confirmar</SubmitButton></form></details>}</li>;
      })}</ul>:<p className="muted">No hay documentos de acreditación registrados.</p>}</section>
    </div>
  </>;
}
