import {randomUUID} from "node:crypto";
import Link from "next/link";
import {notFound,redirect} from "next/navigation";
import {ArrowLeft, Banknote, ReceiptText, Wallet} from "lucide-react";
import {requireActor} from "@/lib/auth";
import {FinanceError,getFinancialService} from "@/lib/finance";
import {addCostAction,registerInvoiceAction,registerPaymentAction,valueServiceAction,voidInvoiceAction} from "@/app/finance-actions";
import {Notice,chileDate} from "@/components/UI";
import {SubmitButton} from "@/components/Transition";

const money=(value:string|number)=>Number(value).toLocaleString("es-CL",{maximumFractionDigits:0});
const dateString=(value:Date|string)=>value instanceof Date?value.toISOString().slice(0,10):String(value).slice(0,10);
export default async function FinancialDetail({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{error?:string;ok?:string}>}){
  const actor=await requireActor();
  if(actor.role!=="admin")redirect("/");
  const {id}=await params;
  let detail;
  try{detail=await getFinancialService(actor,id);}catch(error){if(error instanceof FinanceError)notFound();throw error;}
  const {service,tariffs,payments,costs,voidedInvoices}=detail;
  const query=await searchParams;
  const today=new Intl.DateTimeFormat("sv-SE",{timeZone:"America/Santiago",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
  const remaining=Number(service.invoice_total??0)-Number(service.paid_clp);
  const margin=Number(service.total_clp??0)-Number(service.manual_cost_clp)-Number(service.fuel_cost_clp);
  return <>
    <Link className="back-link" href="/finanzas"><ArrowLeft size={16}/> Contratos y finanzas</Link>
    <div className="page-title-row"><div><div className="eyebrow">ADMINISTRACIÓN DEL SERVICIO</div><h1>RER-{String(service.folio).padStart(5,"0")}</h1><p className="page-intro">{service.client_name} · {service.site_name} · {service.waste_type}</p></div><Link className="button button-outline" href={`/solicitudes/${id}`}>Ver operación</Link></div>
    <Notice error={query.error} ok={query.ok}/>
    <div className="supply-summary"><div><strong>{service.total_clp!==null?`$${money(service.total_clp)}`:"—"}</strong><span>Valor neto registrado</span></div><div><strong>{service.invoice_total!==null?`$${money(remaining)}`:"—"}</strong><span>Por cobrar</span></div><div><strong>{service.total_clp!==null?`$${money(margin)}`:"—"}</strong><span>Margen estimado</span></div></div>
    {service.status!=="completada"&&<p className="notice notice-error">Cierre el servicio antes de valorizarlo o registrar costos.</p>}
    <div className="supply-columns"><div>
      <section className="section-card"><div className="section-heading"><div><div className="eyebrow">VALORIZACIÓN</div><h2><Banknote size={19}/> Tarifa aplicada</h2></div></div>{service.valuation_id?<div className="facts-grid"><div className="fact"><span>Tarifa guardada</span><strong>${money(service.unit_price_clp??0)} por {service.tariff_unit??"unidad"}</strong></div><div className="fact"><span>Cantidad aplicada</span><strong>{Number(service.quantity).toLocaleString("es-CL")} </strong></div><div className="fact"><span>Valor registrado</span><strong>${money(service.total_clp??0)}</strong></div><div className="fact"><span>OC del cliente</span><strong>{service.client_order_reference??"No informada"}</strong></div></div>:<><p className="helper-text">Seleccione una tarifa válida para el cliente y la fecha de cierre; el precio y peso neto se conservan como referencia histórica.</p><form action={valueServiceAction} className="form-stack"><input type="hidden" name="service_id" value={id}/><label>Tarifa vigente<select name="tariff_id" defaultValue="" required><option value="">Seleccione</option>{tariffs.map((tariff)=><option key={tariff.id} value={tariff.id}>{tariff.contract_code} · {tariff.service_type} · {tariff.waste_type??"Todos"} · ${money(tariff.unit_price_clp)}/{tariff.unit}</option>)}</select></label><label>Referencia OC del cliente (opcional)<input name="client_order_reference" maxLength={80}/></label>{!tariffs.length&&<p className="helper-text">Agregue primero un contrato y tarifa aplicable en <Link href="/finanzas">Contratos y finanzas</Link>.</p>}<SubmitButton className="button button-primary" disabled={!tariffs.length||service.status!=="completada"}>Valorizar servicio</SubmitButton></form></>}</section>
      <section className="section-card"><div className="section-heading"><div><div className="eyebrow">COSTOS DIRECTOS</div><h2>Costos imputados</h2></div></div><p className="helper-text">Las cargas de combustible vinculadas a este servicio (${money(service.fuel_cost_clp)}) se suman automáticamente al costo. Registre aquí mano de obra, peajes y otros conceptos sin duplicar combustible.</p><form action={addCostAction} className="form-grid"><input type="hidden" name="service_id" value={id}/><input type="hidden" name="submission_key" value={randomUUID()}/><label>Concepto<select name="category" defaultValue="mano_obra"><option value="mano_obra">Mano de obra</option><option value="disposicion">Disposición</option><option value="peajes">Peajes</option><option value="equipos">Equipos</option><option value="otros">Otros</option></select></label><label>Monto CLP<input name="amount_clp" type="number" min="0.01" step="0.01" required/></label><label className="field-full">Justificación<input name="description" required minLength={5} maxLength={500}/></label><div className="field-full form-footer"><SubmitButton className="button button-outline" disabled={service.status!=="completada"}>Registrar costo</SubmitButton></div></form>{costs.length>0&&<ul className="record-list">{costs.map((cost)=><li key={cost.id}><strong>{cost.description}</strong><small>{cost.category} · ${money(cost.amount_clp)} · {chileDate(cost.created_at)}</small></li>)}</ul>}</section>
    </div><aside><section className="section-card side-card"><div className="eyebrow">FACTURACIÓN INTERNA</div><h2><ReceiptText size={19}/> Factura emitida fuera del sistema</h2>{service.invoice_id?<div className="supply-meta"><div><span>Número</span><strong>{service.invoice_number} · {service.invoice_status}</strong></div><div><span>Total registrado</span><strong>${money(service.invoice_total??0)}</strong></div><div><span>Abonos</span><strong>${money(service.paid_clp)}</strong></div><div><span>Saldo</span><strong>${money(remaining)}</strong></div></div>:<form action={registerInvoiceAction} className="form-stack compact"><input type="hidden" name="service_id" value={id}/><label>Folio de factura<input name="invoice_number" required minLength={2} maxLength={80}/></label><div className="two-fields"><label>Emisión<input name="issued_on" type="date" defaultValue={today} required/></label><label>Vencimiento<input name="due_on" type="date" required/></label></div><SubmitButton className="button button-primary" disabled={!service.valuation_id}>Asociar factura</SubmitButton></form>}{service.invoice_id&&service.invoice_status==="emitida"&&payments.length===0&&<details className="cancel-control"><summary>Marcar factura como anulada</summary><form action={voidInvoiceAction} className="form-stack compact"><input type="hidden" name="service_id" value={id}/><input type="hidden" name="invoice_id" value={service.invoice_id}/><input name="reason" required minLength={5} maxLength={500} placeholder="Motivo"/><SubmitButton className="button button-outline">Confirmar</SubmitButton></form></details>}</section>
      {service.invoice_id&&service.invoice_status==="emitida"&&remaining>0&&<section className="section-card side-card"><div className="eyebrow">COBRANZA</div><h2><Wallet size={19}/> Registrar pago</h2><form action={registerPaymentAction} className="form-stack compact"><input type="hidden" name="service_id" value={id}/><input type="hidden" name="invoice_id" value={service.invoice_id}/><input type="hidden" name="submission_key" value={randomUUID()}/><label>Monto del abono (máximo ${money(remaining)})<input name="amount_clp" type="number" min="0.01" step="0.01" required/></label><label>Fecha de pago<input name="paid_on" type="date" defaultValue={today} required/></label><label>Medio<select name="method" defaultValue="transferencia"><option value="transferencia">Transferencia</option><option value="efectivo">Efectivo</option><option value="tarjeta">Tarjeta</option><option value="otro">Otro</option></select></label><label>Referencia bancaria o comprobante<input name="reference" minLength={2} maxLength={120} required/></label><SubmitButton className="button button-outline">Registrar abono</SubmitButton></form></section>}
      {payments.length>0&&<section className="section-card side-card"><div className="eyebrow">HISTORIAL DE COBROS</div><h2>Abonos registrados</h2><ul className="record-list">{payments.map((payment)=><li key={payment.id}><strong>${money(payment.amount_clp)}</strong><small>{payment.method} · {payment.reference} · {dateString(payment.paid_on)} · {payment.actor_name}</small></li>)}</ul></section>}
      {voidedInvoices.length>0&&<section className="section-card side-card"><div className="eyebrow">HISTORIAL</div><h2>Facturas anuladas</h2><ul className="record-list">{voidedInvoices.map((invoice)=><li key={invoice.invoice_number}><strong>{invoice.invoice_number}</strong><small>{chileDate(invoice.created_at)} · anulada</small></li>)}</ul></section>}
    </aside></div>
  </>;
}
