import { randomUUID } from "node:crypto";
import Link from "next/link";
import { redirect } from "next/navigation";
import { Fuel, TrendingUp, ArrowRight } from "lucide-react";
import { canManage, requireActor } from "@/lib/auth";
import { listFuel } from "@/lib/continuity";
import { registerFuelAction } from "@/app/continuity-actions";
import { Notice, chileDate } from "@/components/UI";
import { SubmitButton } from "@/components/Transition";

const amount=(value:number|string,digits=2)=>Number(value).toLocaleString("es-CL",{maximumFractionDigits:digits});
export default async function FuelPage({searchParams}:{searchParams:Promise<{error?:string;ok?:string}>}) {
  const actor=await requireActor();
  if (!canManage(actor)) redirect("/");
  const [{assets,drivers,services,entries},query]=await Promise.all([listFuel(actor),searchParams]);
  const totalLiters=entries.reduce((sum,entry)=>sum+Number(entry.liters),0);
  const totalCost=entries.reduce((sum,entry)=>sum+Number(entry.cost_clp),0);
  const today=new Intl.DateTimeFormat("sv-SE",{timeZone:"America/Santiago",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
  return <>
    <div className="page-title-row"><div><div className="eyebrow">COSTOS OPERACIONALES</div><h1>Combustible y rendimiento</h1><p className="page-intro">Cada carga queda asociada al activo, lectura, conductor, comprobante y servicio cuando corresponde.</p></div><span className="title-icon"><Fuel size={23}/></span></div>
    <Notice error={query.error} ok={query.ok}/>
    <div className="supply-summary"><div><strong>{entries.length}</strong><span>Cargas recientes</span></div><div><strong>{amount(totalLiters)}</strong><span>Litros registrados</span></div><div><strong>${amount(totalCost,0)}</strong><span>Costo de las cargas visibles</span></div><Link href="/mantenimiento" className="button button-outline">Lecturas de activos <ArrowRight size={16}/></Link></div>
    <div className="supply-columns"><section className="section-card"><div className="section-heading"><div><div className="eyebrow">REGISTRO</div><h2><Fuel size={19}/> Nueva carga</h2></div></div><form action={registerFuelAction} className="form-stack"><input type="hidden" name="submission_key" value={randomUUID()}/><label>Activo<select name="asset_id" required defaultValue=""><option value="">Seleccione activo</option>{assets.filter((asset)=>asset.reading_unit!=="sin").map((asset)=><option key={asset.id} value={asset.id}>{asset.code} · {asset.label} · {amount(asset.current_reading)} {asset.reading_unit}</option>)}</select></label><div className="two-fields"><label>Fecha<input name="fuel_date" type="date" required defaultValue={today}/></label><label>Conductor (opcional)<select name="driver_id" defaultValue=""><option value="">No asociado</option>{drivers.map((driver)=><option key={driver.id} value={driver.id}>{driver.name}</option>)}</select></label></div><label>Servicio asociado (opcional)<select name="service_id" defaultValue=""><option value="">Sin servicio</option>{services.map((service)=><option key={service.id} value={service.id}>RER-{String(service.folio).padStart(5,"0")} · {assets.find((asset)=>asset.id===service.asset_id)?.label??"Activo"}</option>)}</select></label><div className="two-fields"><label>Litros<input name="liters" type="number" min="0.001" step="0.001" required/></label><label>Costo total ($ CLP)<input name="cost_clp" type="number" min="0" step="0.01" required/></label></div><label>Lectura del activo (km/horas)<input name="reading" type="number" min="0" step="0.01" required/></label><label className="check-row"><input name="full_tank" type="checkbox"/> Tanque completo (permite estimar rendimiento entre cargas completas consecutivas)</label><div className="two-fields"><label>Proveedor<input name="supplier" required minLength={2} maxLength={160}/></label><label>Número de comprobante<input name="receipt_number" required minLength={2} maxLength={80}/></label></div><label>Observaciones<textarea name="notes" rows={2} maxLength={1000}/></label><SubmitButton className="button button-primary" disabled={!assets.some((asset)=>asset.reading_unit!=="sin")}>Registrar carga</SubmitButton></form></section>
      <section className="section-card"><div className="section-heading"><div><div className="eyebrow">HISTORIAL</div><h2><TrendingUp size={19}/> Consumo por activo</h2></div></div><p className="helper-text">El rendimiento aproximado se muestra sólo entre dos cargas de tanque completo consecutivas. Las cargas parciales permanecen en el historial sin estimación.</p>{entries.length?<div className="table-wrap"><table className="data-table"><thead><tr><th>Fecha / activo</th><th>Carga</th><th>Costo</th><th>Lectura</th><th>Rendimiento</th></tr></thead><tbody>{entries.map((entry)=><tr key={entry.id}><td>{chileDate(`${entry.fuel_date instanceof Date?entry.fuel_date.toISOString().slice(0,10):String(entry.fuel_date).slice(0,10)}T12:00:00Z`,false)}<span className="table-sub">{entry.asset_code} · {entry.asset_label}{entry.driver_name?` · ${entry.driver_name}`:""}</span></td><td>{amount(entry.liters,3)} L<span className="table-sub">{entry.supplier} · {entry.receipt_number}{entry.service_folio?` · RER-${entry.service_folio}`:""}</span></td><td>${amount(entry.cost_clp,0)}</td><td>{amount(entry.reading)}</td><td>{entry.km_per_liter?`${amount(entry.km_per_liter,3)} km/L`:"—"}</td></tr>)}</tbody></table></div>:<p className="muted">No hay cargas registradas.</p>}</section></div>
  </>;
}
