import Link from "next/link";
import { redirect } from "next/navigation";
import { Container, MapPin, ArrowLeftRight, AlertTriangle } from "lucide-react";
import { canManage, requireActor } from "@/lib/auth";
import { listContainers } from "@/lib/containers";
import { createContainerAction, moveContainerAction,recordContainerServiceAction } from "@/app/container-actions";
import { Notice, chileDate } from "@/components/UI";
import { SubmitButton } from "@/components/Transition";

const statuses:Record<string,string>={patio:"En patio",instalada:"Instalada",en_transito:"En tránsito",fuera_servicio:"Fuera de servicio"};
export default async function Containers({searchParams}:{searchParams:Promise<{error?:string;ok?:string}>}) {
  const actor=await requireActor();
  if (!canManage(actor)) redirect("/");
  const [{containers,sites,services,movements,records},query]=await Promise.all([listContainers(actor),searchParams]);
  const overdue=containers.filter((c)=>c.status==="instalada" && c.stay_days>=c.max_stay_days);
  return <>
    <div className="page-title-row"><div><div className="eyebrow">UNIDADES EN TERRENO</div><h1>Tolvas y contenedores</h1><p className="page-intro">Ubicación actual, contenido, tiempo de permanencia y traslados con historial.</p></div><span className="title-icon"><Container size={23}/></span></div>
    <Notice error={query.error} ok={query.ok}/>
    <div className="supply-summary"><div><strong>{containers.length}</strong><span>Unidades registradas</span></div><div><strong>{containers.filter((c)=>c.status==="instalada").length}</strong><span>Instaladas en faena</span></div><div><strong>{overdue.length}</strong><span>Permanencias por revisar</span></div></div>
    {overdue.length>0&&<div className="resource-alert"><strong><AlertTriangle size={16}/> Unidades que alcanzaron el plazo de revisión</strong><span>{overdue.map((c)=>`${c.code} (${c.stay_days} días en ${c.site_name})`).join(" · ")}</span></div>}
    <section className="section-card"><div className="section-heading"><div><div className="eyebrow">UBICACIÓN VIGENTE</div><h2><MapPin size={19}/> Inventario de unidades</h2></div><span className="count-pill">{containers.length}</span></div>
      {containers.length?<div className="table-wrap"><table className="data-table"><thead><tr><th>Unidad</th><th>Estado</th><th>Ubicación / contenido</th><th>Permanencia</th><th>Gestionar</th></tr></thead><tbody>{containers.map((c)=><tr key={c.id}><td><strong>{c.code}</strong><span className="table-sub">{c.kind} · {Number(c.capacity_m3).toLocaleString("es-CL")} m³</span></td><td><span className={`badge container-${c.status}`}>{statuses[c.status]}</span></td><td>{c.location_name}<span className="table-sub">{c.waste_type||"Sin contenido registrado"}</span></td><td>{c.status==="instalada"?<span className={c.stay_days>=c.max_stay_days?"inventory-low":"inventory-good"}>{c.stay_days} días · umbral {c.max_stay_days}</span>:"—"}</td><td><details className="container-control"><summary>Registrar movimiento</summary><form action={moveContainerAction} className="form-stack compact"><input type="hidden" name="container_id" value={c.id}/><label>Acción<select name="action" defaultValue={c.status==="instalada"?"retirar":"instalar"}><option value="instalar">Instalar en faena</option><option value="retirar">Retirar a patio</option><option value="reubicar">Reubicar en otra faena</option><option value="traslado">Enviar en tránsito</option><option value="fuera_servicio">Fuera de servicio</option><option value="reactivar">Reactivar en patio</option></select></label><label>Faena de destino (al instalar/reubicar)<select name="site_id" defaultValue=""><option value="">Sin faena</option>{sites.map((site)=><option key={site.id} value={site.id}>{site.client_name} · {site.name}</option>)}</select></label><label>Ubicación en patio, tránsito o taller (al retirar/trasladar)<input name="location_name" maxLength={180} placeholder="Patio RERCHAR"/></label><label>Contenido o residuo (al instalar)<input name="waste_type" maxLength={120}/></label><label>Servicio asociado (opcional)<select name="service_id" defaultValue=""><option value="">Sin vínculo</option>{services.map((service)=><option key={service.id} value={service.id}>RER-{String(service.folio).padStart(5,"0")} · {sites.find((site)=>site.id===service.site_id)?.name??"Faena"}</option>)}</select></label><label>Motivo<textarea name="note" required minLength={5} maxLength={500} rows={2}/></label><SubmitButton className="button button-outline">Guardar movimiento</SubmitButton></form></details></td></tr>)}</tbody></table></div>:<p className="muted">Registre una unidad para comenzar el control de ubicaciones.</p>}
    </section>
    <section className="section-card"><div className="section-heading"><div><div className="eyebrow">ARRIENDOS Y TRASLADOS</div><h2>Kilometrajes y mantenciones de tolvas</h2></div></div><form action={recordContainerServiceAction} className="form-grid"><label>Unidad<select name="container_id" defaultValue="" required><option value="">Seleccione</option>{containers.map(c=><option key={c.id} value={c.id}>{c.code} · {c.kind}</option>)}</select></label><label>Tipo<select name="kind" defaultValue="kilometraje"><option value="kilometraje">Kilometraje de traslado / arriendo</option><option value="mantenimiento">Mantención</option></select></label><label>Fecha<input name="record_date" type="date" required/></label><label>Servicio asociado (opcional)<select name="service_id" defaultValue=""><option value="">Sin vínculo</option>{services.map(s=><option key={s.id} value={s.id}>RER-{String(s.folio).padStart(5,"0")}</option>)}</select></label><label>Kilómetros recorridos<input name="kilometers" type="number" min="0" step="0.01" placeholder="Sólo si corresponde"/></label><label>Costo de mantención (CLP)<input name="cost_clp" type="number" min="0" step="0.01"/></label><label className="field-full">Detalle<input name="description" required minLength={5} maxLength={500} placeholder="Ej. Traslado a faena / cambio de bisagras"/></label><div className="field-full form-footer"><SubmitButton className="button button-outline" disabled={!containers.length}>Registrar</SubmitButton></div></form>{records.length>0&&<ul className="record-list">{records.slice(0,30).map(r=><li key={r.id}><strong>{r.code} · {r.kind}</strong><small>{r.record_date instanceof Date?r.record_date.toISOString().slice(0,10):String(r.record_date).slice(0,10)} · {r.description}{r.kilometers!==null?` · ${Number(r.kilometers).toLocaleString("es-CL")} km`:""}{r.cost_clp!==null?` · $${Number(r.cost_clp).toLocaleString("es-CL")}`:""}</small></li>)}</ul>}</section>
    <div className="supply-columns"><section className="section-card"><div className="section-heading"><div><div className="eyebrow">CATÁLOGO</div><h2><Container size={19}/> Nueva unidad</h2></div></div><form action={createContainerAction} className="form-stack"><div className="two-fields"><label>Código único<input name="code" required minLength={2} maxLength={45} placeholder="TOL-001"/></label><label>Tipo<select name="kind" defaultValue="tolva"><option value="tolva">Tolva</option><option value="ampliroll">Ampliroll</option><option value="contenedor">Contenedor</option></select></label></div><div className="two-fields"><label>Capacidad (m³)<input name="capacity_m3" type="number" min="0.01" step="0.01" required/></label><label>Revisar permanencia desde (días)<input name="max_stay_days" type="number" min="1" max="3650" defaultValue="14" required/></label></div><label>Ubicación inicial / patio<input name="location_name" required minLength={2} maxLength={180} placeholder="Patio principal"/></label><SubmitButton className="button button-primary">Registrar unidad</SubmitButton></form></section>
      <section className="section-card"><div className="section-heading"><div><div className="eyebrow">TRAZABILIDAD</div><h2><ArrowLeftRight size={19}/> Movimientos recientes</h2></div></div>{movements.length?<ol className="container-events">{movements.map((m)=><li key={m.id}><strong>{m.code} · {m.kind.replaceAll("_"," ")}</strong><span>{m.previous_location?`${m.previous_location} → `:""}{m.next_location}</span><small>{m.actor_name} · {chileDate(m.created_at)}{m.service_id?<> · <Link href={`/solicitudes/${m.service_id}`}>RER-{String(m.service_folio).padStart(5,"0")}</Link></>:null}</small><span>{m.note}</span></li>)}</ol>:<p className="muted">El historial se genera con cada instalación o retiro.</p>}</section></div>
  </>;
}
