import assert from "node:assert/strict";
import { readFile, mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { randomUUID } from "node:crypto";
import test from "node:test";
import type { Actor } from "../lib/auth";

test("solicitud, permisos, planificación, checklist, evidencia y cierre", async () => {
  process.env.PGLITE_DATA_DIR = "memory://";
  const uploadDir = await mkdtemp(join(tmpdir(), "rerchar-test-"));
  process.env.STORAGE_DIR = uploadDir;
  try {
    const { db, transaction } = await import("../lib/db");
    const { createClient, createSite, createAsset, createService, assignService, cancelService, reportFleetIncident, resolveFleetIncident, listFleet, reportServices, normalizeReportFilters, saveChecklist, startService, addEvidence, finishService, getService, listServices, listAgenda, PilotError } = await import("../lib/pilot");
    for (const migration of ["001_piloto.sql", "002_flota_y_despacho.sql", "003_abastecimiento.sql", "004_mantenimiento_combustible.sql", "005_contenedores.sql", "006_acreditacion.sql", "007_finanzas.sql", "008_trazabilidad_ambiental.sql", "009_certificados.sql", "010_evidencia_persistente.sql", "011_operacion_real_2026.sql"]) {
      const sql = await readFile(resolve(process.cwd(), `db/${migration}`), "utf8");
      await transaction(async (tx) => {
        for (const statement of sql.split(/;\s*(?:\n|$)/).map((text) => text.trim()).filter(Boolean)) await tx.query(statement);
      });
    }
    const [a, b] = await db.query<{ id: string }>("INSERT INTO clients (name) VALUES ('Cliente A'), ('Cliente B') RETURNING id");
    const [siteA] = await db.query<{ id: string }>("INSERT INTO client_sites (client_id,name) VALUES ($1,'Faena A') RETURNING id", [a.id]);
    const [siteB] = await db.query<{ id: string }>("INSERT INTO client_sites (client_id,name) VALUES ($1,'Faena B') RETURNING id", [b.id]);
    const [admin] = await db.query<{ id: string }>("INSERT INTO users (email,name,password_hash,role) VALUES ('admin@demo.cl','Administración','hash','admin') RETURNING id");
    const [driver] = await db.query<{ id: string }>("INSERT INTO users (email,name,password_hash,role) VALUES ('chofer@demo.cl','Conductor','hash','conductor') RETURNING id");
    const [clientA] = await db.query<{ id: string }>("INSERT INTO users (email,name,password_hash,role,client_id) VALUES ('cliente@demo.cl','Cliente','hash','cliente',$1) RETURNING id", [a.id]);
    const [clientB] = await db.query<{ id: string }>("INSERT INTO users (email,name,password_hash,role,client_id) VALUES ('otro@demo.cl','Otro','hash','cliente',$1) RETURNING id", [b.id]);
    const [asset] = await db.query<{ id: string }>("INSERT INTO assets (code,label,kind) VALUES ('CAM-01','Camión prueba','camion') RETURNING id");
    const owner: Actor = { id: clientA.id, name: "Cliente", email: "cliente@demo.cl", role: "cliente", client_id: a.id };
    const outsider: Actor = { id: clientB.id, name: "Otro", email: "otro@demo.cl", role: "cliente", client_id: b.id };
    const planner: Actor = { id: admin.id, name: "Administración", email: "admin@demo.cl", role: "admin", client_id: null };
    const operator: Actor = { id: driver.id, name: "Conductor", email: "chofer@demo.cl", role: "conductor", client_id: null };
    await assert.rejects(() => createClient(owner, { name: "Sin permiso" }), PilotError);
    const addedClient = await createClient(planner, { name: "Cliente temporal", tax_id: "", contact_name: "" });
    const addedSite = await createSite(planner, { client_id: addedClient, name: "Centro temporal", address: "Calama" });
    const addedAsset = await createAsset(planner, { code: "CAM-02", label: "Segundo camión", kind: "camion", plate: "" });
    assert.ok(addedSite && addedAsset);
    const [masterAudits] = await db.query<{ total: string }>("SELECT count(*)::text AS total FROM audit_events WHERE actor_id=$1", [planner.id]);
    assert.equal(Number(masterAudits.total), 3);
    const ramp = await createAsset(planner, { code: "RAM-01", label: "Rampa de prueba", kind: "rampa", plate: "" });
    const [otherDriver] = await db.query<{ id: string }>("INSERT INTO users (email,name,password_hash,role) VALUES ('otro-conductor@demo.cl','Segundo conductor','hash','conductor') RETURNING id");
    const submissionKey = randomUUID();
    const input = { submission_key: submissionKey, client_id: a.id, site_id: siteA.id, service_type: "retiro", waste_type: "Chatarra metálica", estimated_kg: "850", origin: "Faena A", destination: "Puerto Seco", priority: "alta", notes: "Prueba" };
    await assert.rejects(() => createService(outsider, input), PilotError);
    await assert.rejects(() => createService(owner, { ...input, site_id: siteB.id }), PilotError);
    const id = await createService(owner, input);
    assert.equal(await createService(owner, input), id, "la repetición con la misma clave no duplica la solicitud");
    assert.equal((await listServices(owner)).length, 1);
    assert.equal((await listServices(outsider)).length, 0);
    await assert.rejects(() => getService(outsider, id), PilotError);
    await assert.rejects(() => assignService(operator, id, { asset_id: asset.id, driver_id: driver.id, scheduled_for: "2026-09-25T09:00" }), PilotError);
    await assignService(planner, id, { asset_id: asset.id, ramp_asset_id: ramp, driver_id: driver.id, scheduled_for: "2026-09-25T09:00", guide_number: "G-001" });
    assert.equal((await getService(planner, id)).ramp_label, "Rampa de prueba");
    assert.equal((await listAgenda(planner, "2026-09-21", "2026-09-28")).length, 1);
    assert.equal((await listAgenda(owner, "2026-09-21", "2026-09-28")).length, 1);
    assert.equal((await listAgenda(outsider, "2026-09-21", "2026-09-28")).length, 0);
    assert.equal((await listAgenda(operator, "2026-09-21", "2026-09-28")).length, 1);
    const competing = await createService(planner, { ...input, submission_key: randomUUID() });
    await assert.rejects(() => assignService(planner, competing, { asset_id: asset.id, driver_id: driver.id, scheduled_for: "2026-09-25T09:30" }), PilotError);
    await assert.rejects(() => assignService(planner, competing, { asset_id: addedAsset, ramp_asset_id: ramp, driver_id: otherDriver.id, scheduled_for: "2026-09-25T09:30" }), PilotError);
    await assert.rejects(() => cancelService(operator, competing, "Cancelado por cliente"), PilotError);
    await cancelService(planner, competing, "Cancelado por cliente");
    assert.equal((await getService(planner, competing)).status, "cancelada");
    assert.equal((await getService(operator, id)).status, "programada");
    await assert.rejects(() => startService(operator, id), PilotError);
    await saveChecklist(operator, id, { vehicle_ok: true, documents_ok: true, containment_ok: false, ppe_ok: true, comment: "Pendiente" });
    await assert.rejects(() => startService(operator, id), PilotError);
    await saveChecklist(operator, id, { vehicle_ok: true, documents_ok: true, containment_ok: true, ppe_ok: true, comment: "Conforme" });
    await assert.rejects(() => listFleet(owner), PilotError);
    const incident1 = await reportFleetIncident(planner, { asset_id: asset.id, description: "Falla de frenos", severity: "critica" });
    const incident2 = await reportFleetIncident(planner, { asset_id: asset.id, description: "Fuga hidráulica", severity: "alta" });
    const fleet = await listFleet(planner);
    assert.equal(fleet.assets.find((a) => a.id === asset.id)?.available, false);
    assert.equal(fleet.incidents.length, 2);
    await assert.rejects(() => startService(operator, id), PilotError);
    await resolveFleetIncident(planner, incident1, "Frenos revisados y reparados");
    assert.equal((await listFleet(planner)).assets.find((a) => a.id === asset.id)?.available, false);
    await resolveFleetIncident(planner, incident2, "Fuga reparada y prueba de presión conforme");
    assert.equal((await listFleet(planner)).assets.find((a) => a.id === asset.id)?.available, true);
    await startService(operator, id);
    await assert.rejects(() => finishService(operator, id, { gross_kg: 1400, tare_kg: 800 }), PilotError);
    await assert.rejects(() => addEvidence(outsider, id, "Imagen del pesaje", new File([new Uint8Array([0xff, 0xd8, 0xff, 0xd9])], "prueba.jpg", { type: "image/jpeg" })), PilotError);
    await addEvidence(operator, id, "Imagen del pesaje", new File([new Uint8Array([0xff, 0xd8, 0xff, 0xd9])], "prueba.jpg", { type: "image/jpeg" }));
    await assert.rejects(() => finishService(operator, id, { gross_kg: 700, tare_kg: 800 }), PilotError);
    await finishService(operator, id, { gross_kg: 1400, tare_kg: 800, guide_number: "G-001" });
    const closed = await getService(owner, id);
    assert.equal(closed.status, "completada");
    await assert.rejects(() => cancelService(planner, id, "Cancelación tardía"), PilotError);
    assert.equal(Number(closed.gross_kg) - Number(closed.tare_kg), 600);
    const completed = normalizeReportFilters({ status: "completada" });
    assert.equal((await reportServices(owner, completed)).length, 1);
    assert.equal((await reportServices(operator, completed)).length, 1);
    assert.equal((await reportServices(outsider, completed)).length, 0);
    assert.equal((await reportServices(planner, normalizeReportFilters({ status: "cancelada" }))).length, 1);
    assert.equal((await reportServices(planner, normalizeReportFilters({ from: "2100-01-01" }))).length, 0);
    assert.equal((await reportServices(planner, normalizeReportFilters({ client_id: b.id }))).length, 0);
    assert.equal(normalizeReportFilters({ from: "2026-02-31" }).from, "");
    const [count] = await db.query<{ total: string }>("SELECT count(*)::text AS total FROM service_events WHERE service_id=$1", [id]);
    assert.equal(Number(count.total), 7);
    assert.equal((await db.query("SELECT id FROM service_requests WHERE submission_key=$1", [submissionKey])).length, 1);
  } finally {
    await rm(uploadDir, { recursive: true, force: true });
  }
});
