import Link from "next/link";
import { notFound,redirect } from "next/navigation";
import { ArrowLeft, Wrench, BookmarkCheck, CheckCircle2 } from "lucide-react";
import { canManage, requireActor } from "@/lib/auth";
import { db } from "@/lib/db";
import { getWorkOrder, ContinuityError } from "@/lib/continuity";
import { startWorkOrderAction, reserveWorkOrderAction, closeWorkOrderAction, cancelWorkOrderAction } from "@/app/continuity-actions";
import { Notice, chileDate } from "@/components/UI";
import { SubmitButton } from "@/components/Transition";

const money=(value:string)=>Number(value).toLocaleString("es-CL",{maximumFractionDigits:0});
export default async function WorkOrderDetail({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{error?:string;ok?:string}>}) {
  const actor=await requireActor();
  if (!canManage(actor)) redirect("/");
  const {id}=await params;
  let detail;
  try { detail=await getWorkOrder(actor,id); } catch(error) { if(error instanceof ContinuityError) notFound(); throw error; }
  const {order,reservations,history}=detail;
  const [items,warehouses,query]=await Promise.all([
    db.query<{id:string;code:string;name:string;unit:string}>("SELECT id,code,name,unit FROM stock_items WHERE active=true ORDER BY name"),
    db.query<{id:string;code:string;name:string}>("SELECT id,code,name FROM warehouses WHERE active=true ORDER BY name"),
    searchParams,
  ]);
  return <>
    <Link className="back-link" href="/mantenimiento"><ArrowLeft size={16}/> Mantenimiento</Link>
    <div className="page-title-row"><div><div className="eyebrow">ORDEN DE TRABAJO</div><h1>OT-{String(order.folio).padStart(5,"0")}</h1><p className="page-intro">{order.title} · {order.asset_code} / {order.asset_label}</p></div><span className={`badge supply-status-${order.status}`}>{order.status==="en_trabajo"?"En trabajo":order.status}</span></div>
    <Notice error={query.error} ok={query.ok}/>
    <div className="supply-columns"><div>
      <section className="section-card"><div className="section-heading"><div><div className="eyebrow">ALCANCE</div><h2><Wrench size={19}/> Trabajo registrado</h2></div></div><div className="facts-grid"><div className="fact"><span>Tipo</span><strong className="capitalize">{order.kind}</strong></div><div className="fact"><span>Planificada para</span><strong>{order.scheduled_for?chileDate(`${order.scheduled_for instanceof Date?order.scheduled_for.toISOString().slice(0,10):String(order.scheduled_for).slice(0,10)}T12:00:00Z`,false):"Sin fecha"}</strong></div><div className="fact"><span>Solicitada por</span><strong>{order.created_by_name}</strong></div><div className="fact"><span>Creada</span><strong>{chileDate(order.created_at)}</strong></div><div className="fact"><span>Vinculada a</span><strong>{order.incident_id?"Avería":"Plan o trabajo manual"}</strong></div><div className="fact"><span>Inmovilización</span><strong>{order.blocks_asset?"Al iniciar":"Sin bloqueo por esta orden"}</strong></div></div>{order.description&&<div className="note-block"><span>Descripción</span><p>{order.description}</p></div>}</section>
      {order.status==="abierta"&&<section className="section-card"><div className="section-heading"><div><div className="eyebrow">EJECUCIÓN</div><h2>Iniciar trabajo</h2></div></div><p className="helper-text">Si la orden requiere inmovilizar el activo, quedará fuera de nuevas asignaciones al iniciar.</p><form action={startWorkOrderAction}><input name="order_id" type="hidden" value={id}/><SubmitButton className="button button-primary">Iniciar orden</SubmitButton></form></section>}
      {["abierta","en_trabajo"].includes(order.status)&&<section className="section-card"><div className="section-heading"><div><div className="eyebrow">REPUESTOS</div><h2><BookmarkCheck size={19}/> Reservar desde bodega</h2></div></div><p className="helper-text">Al cerrar la orden se consumirán automáticamente las reservas activas; el Kardex mostrará ambos movimientos.</p><form action={reserveWorkOrderAction} className="form-grid"><input type="hidden" name="order_id" value={id}/><label>Artículo<select name="item_id" defaultValue="" required><option value="">Seleccione</option>{items.map((item)=><option key={item.id} value={item.id}>{item.code} · {item.name} ({item.unit})</option>)}</select></label><label>Bodega<select name="warehouse_id" defaultValue="" required><option value="">Seleccione</option>{warehouses.map((warehouse)=><option key={warehouse.id} value={warehouse.id}>{warehouse.name}</option>)}</select></label><label>Cantidad<input name="quantity" type="number" min="0.001" step="0.001" required/></label><label>Uso previsto<input name="reason" required minLength={5} maxLength={500} placeholder="Ej. Cambio filtro hidráulico"/></label><div className="field-full form-footer"><SubmitButton className="button button-outline" disabled={!items.length||!warehouses.length}>Reservar repuesto</SubmitButton></div></form></section>}
      {order.status==="en_trabajo"&&<section className="section-card"><div className="section-heading"><div><div className="eyebrow">CIERRE</div><h2><CheckCircle2 size={19}/> Resultado y costos</h2></div></div><form action={closeWorkOrderAction} className="form-grid"><input type="hidden" name="order_id" value={id}/><label className="field-full">Trabajo realizado y prueba de funcionamiento<textarea name="resolution" required minLength={5} maxLength={1600} rows={4}/></label><label>Proveedor o taller<input name="supplier" maxLength={150}/></label><label>Lectura al cierre (opcional)<input name="reading" type="number" min="0" step="0.01"/></label><label>Mano de obra ($ CLP)<input name="labor_cost" type="number" min="0" step="0.01" defaultValue="0" required/></label><label>Repuestos / otros ($ CLP)<input name="parts_cost" type="number" min="0" step="0.01" defaultValue="0" required/></label><div className="field-full form-footer"><SubmitButton className="button button-primary">Cerrar orden y consumir reservas</SubmitButton></div></form></section>}
      {order.status==="cerrada"&&<section className="section-card completion-card"><h2><CheckCircle2 size={19}/> Trabajo cerrado</h2><p>{order.resolution}</p><div className="facts-grid"><div className="fact"><span>Mano de obra</span><strong>${money(order.labor_cost)}</strong></div><div className="fact"><span>Repuestos / otros</span><strong>${money(order.parts_cost)}</strong></div><div className="fact"><span>Costo total registrado</span><strong>${money(String(Number(order.labor_cost)+Number(order.parts_cost)))}</strong></div><div className="fact"><span>Fecha y responsable</span><strong>{chileDate(order.closed_at)} · {order.closed_by_name}</strong></div></div></section>}
      {order.status==="abierta"&&<details className="cancel-control section-card"><summary>Cancelar esta orden</summary><form action={cancelWorkOrderAction} className="form-stack compact"><input type="hidden" name="order_id" value={id}/><label>Motivo<input name="reason" required minLength={5} maxLength={500}/></label><SubmitButton className="button button-outline">Confirmar cancelación</SubmitButton></form></details>}
    </div><aside><section className="section-card side-card"><div className="eyebrow">BODEGA</div><h2>Repuestos vinculados</h2>{reservations.length?<ul className="record-list">{reservations.map((reservation)=><li key={reservation.id}><strong>{reservation.item_name}</strong><small>{Number(reservation.quantity).toLocaleString("es-CL")} {reservation.unit} · {reservation.warehouse_name} · {reservation.status}</small></li>)}</ul>:<p className="muted">Esta orden no tiene repuestos reservados.</p>}<Link href="/inventario" className="back-link">Ver Kardex <ArrowLeft size={14}/></Link></section><section className="section-card side-card"><div className="eyebrow">AUDITORÍA</div><h2>Movimientos de la orden</h2><ol className="timeline">{history.map((event)=><li key={event.id}><span className="timeline-marker"/><strong>{event.action}</strong><small>{event.actor_name} · {chileDate(event.created_at)}</small></li>)}</ol></section></aside></div>
  </>;
}
