import Link from "next/link";
import { redirect } from "next/navigation";
import { Banknote, FileText, ArrowRight, ReceiptText } from "lucide-react";
import { requireActor } from "@/lib/auth";
import { listFinance } from "@/lib/finance";
import { createContractAction, createTariffAction } from "@/app/finance-actions";
import { Notice, chileDate } from "@/components/UI";
import { SubmitButton } from "@/components/Transition";

const money=(value:number|string)=>Number(value).toLocaleString("es-CL",{maximumFractionDigits:0});
const dateString=(value:Date|string)=>value instanceof Date?value.toISOString().slice(0,10):String(value).slice(0,10);
export default async function Finance({searchParams}:{searchParams:Promise<{error?:string;ok?:string}>}){
  const actor=await requireActor();
  if(actor.role!=="admin")redirect("/");
  const [{services,contracts,tariffs,clients,sites},query]=await Promise.all([listFinance(actor),searchParams]);
  const valued=services.filter((s)=>s.valuation_id);
  const invoiced=services.filter((s)=>s.invoice_id&&s.invoice_status==="emitida");
  const balance=invoiced.reduce((sum,s)=>sum+Number(s.invoice_total)-Number(s.paid_clp),0);
  const today=new Intl.DateTimeFormat("sv-SE",{timeZone:"America/Santiago",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
  return <>
    <div className="page-title-row"><div><div className="eyebrow">CONTROL ADMINISTRATIVO</div><h1>Contratos y finanzas</h1><p className="page-intro">Tarifas vigentes, valorización del servicio, facturas registradas, cobros y costos directos.</p></div><span className="title-icon"><Banknote size={23}/></span></div>
    <Notice error={query.error} ok={query.ok}/>
    <div className="supply-summary"><div><strong>{services.length}</strong><span>Servicios cerrados visibles</span></div><div><strong>{valued.length}</strong><span>Valorizados</span></div><div><strong>{invoiced.length}</strong><span>Facturas asociadas</span></div><div><strong>${money(balance)}</strong><span>Saldo por cobrar visible</span></div></div>
    <section className="section-card"><div className="section-heading"><div><div className="eyebrow">SERVICIOS CERRADOS</div><h2><ReceiptText size={19}/> Estado administrativo</h2></div><span className="count-pill">{services.length}</span></div><p className="helper-text">Valores internos en CLP; la plataforma asocia números de facturas emitidas externamente y registra pagos manuales. No emite documentos tributarios.</p>
      {services.length?<div className="table-wrap"><table className="data-table"><thead><tr><th>Servicio</th><th>Valorización</th><th>Factura</th><th>Cobrado / saldo</th><th>Margen estimado</th></tr></thead><tbody>{services.map((s)=><tr key={s.id}><td><Link className="table-main" href={`/finanzas/${s.id}`}>RER-{String(s.folio).padStart(5,"0")}</Link><span className="table-sub">{s.client_name} · {s.site_name}</span></td><td>{s.total_clp!==null?`$${money(s.total_clp)}`:"Pendiente"}</td><td>{s.invoice_number??"Sin factura"}<span className="table-sub">{s.invoice_status??""}</span></td><td>{s.invoice_total!==null?`$${money(s.paid_clp)} / $${money(Number(s.invoice_total)-Number(s.paid_clp))}`:"—"}</td><td>{s.total_clp!==null?`$${money(Number(s.total_clp)-Number(s.manual_cost_clp)-Number(s.fuel_cost_clp))}`:"—"}</td></tr>)}</tbody></table></div>:<p className="muted">Al cerrar un servicio aparecerá aquí para su valorización.</p>}
    </section>
    <div className="supply-columns"><section className="section-card"><div className="section-heading"><div><div className="eyebrow">CONDICIONES COMERCIALES</div><h2><FileText size={19}/> Registrar contrato</h2></div></div><form action={createContractAction} className="form-stack compact"><label>Cliente<select name="client_id" defaultValue="" required><option value="">Seleccione</option>{clients.map((c)=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Faena (opcional: cubre todas las del cliente)<select name="site_id" defaultValue=""><option value="">Todas las faenas</option>{sites.map((s)=><option key={s.id} value={s.id}>{s.client_name} · {s.name}</option>)}</select></label><label>Referencia contractual<input name="code" required minLength={2} maxLength={80}/></label><div className="two-fields"><label>Inicio<input name="starts_on" type="date" required defaultValue={today}/></label><label>Fin (opcional)<input name="ends_on" type="date"/></label></div><label>Condiciones u observaciones<textarea name="notes" rows={2} maxLength={1000}/></label><SubmitButton className="button button-outline" disabled={!clients.length}>Guardar contrato</SubmitButton></form><ul className="record-list">{contracts.map((c)=><li key={c.id}><strong>{c.code}</strong><small>{c.client_name} · {c.site_name??"Todas las faenas"} · desde {dateString(c.starts_on)}</small></li>)}</ul></section>
      <section className="section-card"><div className="section-heading"><div><div className="eyebrow">TARIFARIO</div><h2><Banknote size={19}/> Nueva tarifa</h2></div></div><form action={createTariffAction} className="form-stack compact"><label>Contrato<select name="contract_id" defaultValue="" required><option value="">Seleccione</option>{contracts.filter((c)=>c.active).map((c)=><option key={c.id} value={c.id}>{c.code} · {c.client_name}</option>)}</select></label><div className="two-fields"><label>Tipo de servicio<select name="service_type" defaultValue="retiro"><option value="retiro">Retiro</option><option value="traslado">Traslado</option><option value="compra">Compra</option><option value="venta">Venta</option><option value="otro">Otro</option></select></label><label>Unidad<select name="unit" defaultValue="servicio"><option value="servicio">Por servicio</option><option value="kg">Por kg neto</option></select></label></div><label>Residuo específico (opcional)<input name="waste_type" maxLength={120} placeholder="Vacío para todos los materiales de este tipo"/></label><label>Precio unitario CLP<input name="unit_price_clp" type="number" min="0" step="0.01" required/></label><div className="two-fields"><label>Vigencia desde<input name="valid_from" type="date" required defaultValue={today}/></label><label>Hasta (opcional)<input name="valid_until" type="date"/></label></div><SubmitButton className="button button-outline" disabled={!contracts.length}>Guardar tarifa</SubmitButton></form><ul className="record-list">{tariffs.map((t)=><li key={t.id}><strong>{t.contract_code} · {t.service_type}</strong><small>{t.waste_type??"Todos los materiales"} · ${money(t.unit_price_clp)}/{t.unit} · desde {dateString(t.valid_from)}</small></li>)}</ul></section></div>
    <Link className="back-link" href="/reportes">Ir a reportes <ArrowRight size={15}/></Link>
  </>;
}
