import Link from "next/link";
import {notFound} from "next/navigation";
import {ArrowLeft,Weight} from "lucide-react";
import {requireActor,canManage} from "@/lib/auth";
import {getService,PilotError} from "@/lib/pilot";
import {guideDifferences,guideValues,listGuideControls} from "@/lib/guides";
import {saveGuideControlAction} from "@/app/guide-actions";
import {Notice} from "@/components/UI";
import {SubmitButton} from "@/components/Transition";
import PrintButton from "@/components/PrintButton";

const showKg=(n:number|null|string)=>n==null?"Pendiente":`${Number(n).toLocaleString("es-CL",{maximumFractionDigits:2})} kg`;
function day(value:Date|string){return new Intl.DateTimeFormat("es-CL",{timeZone:"UTC",dateStyle:"short"}).format(new Date(value));}
const money=(n:number|null)=>n==null?"Pendiente":`$${n.toLocaleString("es-CL")}`;
const iso=(value:Date|string|null)=>!value?"":value instanceof Date?value.toISOString().slice(0,10):String(value).slice(0,10);
export default async function GuidePage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{error?:string;ok?:string;editar?:string}>}){
  const actor=await requireActor();
  const {id}=await params;
  let service;
  try{service=await getService(actor,id);}catch(error){if(error instanceof PilotError)notFound();throw error;}
  const [guides,query]=await Promise.all([listGuideControls(actor,id),searchParams]);
  const editing=guides.find(g=>g.guide_number===query.editar);
  return <>
    <div className="order-actions print-hide"><Link href={`/solicitudes/${id}`} className="back-link"><ArrowLeft size={16}/> Volver al servicio</Link><PrintButton label="Imprimir control / guardar PDF"/></div>
    <div className="print-hide"><Notice error={query.error} ok={query.ok}/></div>
    <article className="order-sheet"><header className="order-header"><div><div className="order-system">RERCHAR CHILE SPA</div><h1>Control de guías y pesajes</h1></div><div className="order-number"><small>SERVICIO</small><h1>RER-{String(service.folio).padStart(5,"0")}</h1></div></header>
      <div className="order-section"><div className="order-grid"><div><small>Cliente / faena</small><strong>{service.client_name} · {service.site_name}</strong></div><div><small>Ruta</small><strong>{service.origin} → {service.destination}</strong></div><div><small>Material</small><strong>{service.waste_type}</strong></div><div><small>Camión / conductor</small><strong>{service.asset_label??"Pendiente"} · {service.driver_name??"Pendiente"}</strong></div></div></div>
      {guides.map(guide=>{const d=guideDifferences(guide),v=guideValues(guide);return <div className="order-section" key={guide.id}><h2>Guía {guide.guide_number} · {day(guide.movement_date)} · {guide.movement_type}</h2>
        <div className="order-grid"><div><small>Chofer / patente</small><strong>{guide.driver_name||"—"} / {guide.truck_plate||"—"}</strong></div><div><small>Material</small><strong>{guide.material_name||"—"}</strong></div><div><small>Ticket faena / origen</small><strong>{guide.origin_ticket||"Pendiente"}</strong></div><div><small>Ticket salida</small><strong>{guide.departure_ticket||"—"}</strong></div><div><small>Peso desde faena</small><strong>{showKg(guide.origin_kg)}</strong></div><div><small>Peso agregado desde stock</small><strong>{showKg(guide.complementary_kg)}</strong></div><div><small>Salida total (faena + stock)</small><strong>{showKg(d.departure_kg)}</strong></div>
          <div><small>Ticket destino</small><strong>{guide.destination_ticket||"Pendiente"}</strong></div><div><small>Peso recibido en destino</small><strong>{showKg(guide.arrival_kg)}</strong></div><div><small>Impurezas / material devuelto</small><strong>{showKg(guide.returned_impurities_kg)}</strong></div><div><small>Diferencia destino - (salida - devuelto)</small><strong>{showKg(d.difference_kg)}</strong></div>
          <div><small>Ticket de retorno</small><strong>{guide.return_ticket||"Pendiente"}</strong></div><div><small>Peso del retorno</small><strong>{showKg(guide.return_weight_kg)}</strong></div><div><small>Impurezas descontadas en destino</small><strong>{showKg(guide.destination_impurities_kg)}</strong></div><div><small>Peso facturado</small><strong>{showKg(guide.invoice_kg)}</strong></div><div><small>Diferencia (destino - impurezas) - factura</small><strong>{showKg(d.invoice_difference_kg)}</strong></div><div><small>Factura / guía valorizada</small><strong>{guide.invoice_number||"—"} / {guide.valued_guide_number||"—"}</strong></div><div><small>Precio acordado / facturado por kg</small><strong>{money(guide.agreed_price_clp==null?null:Number(guide.agreed_price_clp))} / {money(guide.invoice_price_clp==null?null:Number(guide.invoice_price_clp))}</strong></div><div><small>Valor estimado / facturado</small><strong>{money(v.estimated_clp)} / {money(v.billed_clp)}</strong></div><div><small>Diferencia valorizada</small><strong>{money(v.variance_clp)}</strong></div><div><small>Factura emitida / pago</small><strong>{guide.invoice_issued_on?day(guide.invoice_issued_on):"—"} / {guide.payment_on?day(guide.payment_on):"—"}</strong></div><div><small>Transportista / factura flete</small><strong>{guide.freight_company||"—"} / {guide.freight_invoice_number||"—"}</strong></div><div><small>Guía flete / pago requerido</small><strong>{guide.freight_guide_reference||"—"} / {guide.freight_payment_required||"—"}</strong></div></div>
        {guide.notes&&<p>{guide.notes}</p>}{canManage(actor)&&<Link className="back-link print-hide" href={`/solicitudes/${id}/guias?editar=${encodeURIComponent(guide.guide_number)}#editar`}>Editar esta guía</Link>}</div>})}
      {!guides.length&&<p className="order-muted">Aún no se registran guías con control de pesaje.</p>}
      <footer className="order-footer">Registro operativo interno · Las diferencias reflejan las fórmulas del control de guías de 2026.</footer>
    </article>
    {canManage(actor)&&<section id="editar" className="section-card print-hide"><div className="section-heading"><div><div className="eyebrow">GUÍA DE TRASLADO / VALORIZACIÓN</div><h2><Weight size={19}/> {editing?`Actualizar guía ${editing.guide_number}`:"Agregar un control"}</h2></div></div>
      <p className="helper-text">Una fila por guía. Para corregirla, use el mismo número; los campos que deje vacíos conservan su valor anterior. Se registra la auditoría de cada cambio.</p>
      <form action={saveGuideControlAction} className="form-grid"><input type="hidden" name="service_id" value={id}/>
        <label>Número de guía<input name="guide_number" required maxLength={50} defaultValue={editing?.guide_number??""} readOnly={!!editing}/></label><label>Fecha<input name="movement_date" type="date" required defaultValue={iso(editing?.movement_date??null)}/></label>
        <label>Operación<select name="movement_type" defaultValue={editing?.movement_type??(service.request_category==="servicios"?"servicio":service.request_category)}><option value="servicio">Servicio</option><option value="compra">Compra</option><option value="venta">Venta</option><option value="traslado">Traslado</option><option value="otro">Otro</option></select></label><label>Conductor<input name="driver_name" maxLength={120} defaultValue={editing?.driver_name??service.driver_name??""}/></label><label>Patente camión<input name="truck_plate" maxLength={30} defaultValue={editing?.truck_plate??""}/></label><label>Material<input name="material_name" maxLength={160} defaultValue={editing?.material_name??service.waste_type}/></label>
        <div className="form-section-title field-full">Salida de origen</div><label>Ticket faena<input name="origin_ticket" maxLength={80} defaultValue={editing?.origin_ticket??""}/></label><label>Ticket de salida<input name="departure_ticket" maxLength={80} defaultValue={editing?.departure_ticket??""}/></label><label>Peso desde faena (kg)<input name="origin_kg" type="number" min="0" step="0.01" defaultValue={editing?.origin_kg??""}/></label><label>Peso complementario desde stock (kg)<input name="complementary_kg" type="number" min="0" step="0.01" defaultValue={editing?.complementary_kg??""}/></label>
        <div className="form-section-title field-full">Llegada y retorno</div><label>Ticket destino<input name="destination_ticket" maxLength={80} defaultValue={editing?.destination_ticket??""}/></label><label>Peso recibido en destino (kg)<input name="arrival_kg" type="number" min="0" step="0.01" defaultValue={editing?.arrival_kg??""}/></label><label>Impurezas / material devuelto (kg)<input name="returned_impurities_kg" type="number" min="0" step="0.01" defaultValue={editing?.returned_impurities_kg??""}/></label><label>Ticket retorno<input name="return_ticket" maxLength={80} defaultValue={editing?.return_ticket??""}/></label><label>Peso de retorno (kg)<input name="return_weight_kg" type="number" min="0" step="0.01" defaultValue={editing?.return_weight_kg??""}/></label>
        <div className="form-section-title field-full">Factura y respaldo</div><label>Impureza descontada por destino (kg)<input name="destination_impurities_kg" type="number" min="0" step="0.01" defaultValue={editing?.destination_impurities_kg??""}/></label><label>Peso factura (kg)<input name="invoice_kg" type="number" min="0" step="0.01" defaultValue={editing?.invoice_kg??""}/></label><label>Precio acordado ($/kg)<input name="agreed_price_clp" type="number" min="0" step="0.01" defaultValue={editing?.agreed_price_clp??""}/></label><label>Precio facturado ($/kg)<input name="invoice_price_clp" type="number" min="0" step="0.01" defaultValue={editing?.invoice_price_clp??""}/></label><label>Número factura<input name="invoice_number" maxLength={80} defaultValue={editing?.invoice_number??""}/></label><label>Fecha factura<input name="invoice_issued_on" type="date" defaultValue={iso(editing?.invoice_issued_on??null)}/></label><label>Fecha pago<input name="payment_on" type="date" defaultValue={iso(editing?.payment_on??null)}/></label><label>Guía valorizada<input name="valued_guide_number" maxLength={80} defaultValue={editing?.valued_guide_number??""}/></label><div className="form-section-title field-full">Flete asociado</div><label>Transportista<input name="freight_company" maxLength={160} defaultValue={editing?.freight_company??""}/></label><label>Factura flete<input name="freight_invoice_number" maxLength={80} defaultValue={editing?.freight_invoice_number??""}/></label><label>Guía del transportista<input name="freight_guide_reference" maxLength={80} defaultValue={editing?.freight_guide_reference??""}/></label><label>Pago flete requerido<select name="freight_payment_required" defaultValue={editing?.freight_payment_required??""}><option value="">Sin definir</option><option value="si">Sí</option><option value="no">No</option><option value="pendiente">Pendiente</option></select></label><label className="field-full">Observaciones<textarea name="notes" maxLength={500} rows={3} defaultValue={editing?.notes??""}/></label>
        <div className="field-full form-footer"><SubmitButton className="button button-primary">Guardar control de guía</SubmitButton></div>
      </form></section>}
  </>;
}
