import Link from "next/link";
import { redirect } from "next/navigation";
import { Boxes, ArrowUpRight, ArrowLeftRight, BookmarkCheck, Warehouse } from "lucide-react";
import { canManage, requireActor } from "@/lib/auth";
import { listInventory } from "@/lib/supply";
import { adjustStockAction, closeReservationAction, createItemAction, createWarehouseAction, reserveStockAction, transferStockAction } from "@/app/supply-actions";
import { Notice, chileDate } from "@/components/UI";
import { SubmitButton } from "@/components/Transition";

const movementLabel: Record<string, string> = {
  recepcion: "Recepción", ajuste_entrada: "Ajuste +", ajuste_salida: "Ajuste −",
  transferencia_entrada: "Traslado +", transferencia_salida: "Traslado −", reserva: "Reserva",
  liberacion: "Liberación", consumo: "Consumo",
};
const amount = (value: string) => Number(value).toLocaleString("es-CL",{ maximumFractionDigits:3 });

export default async function Inventory({ searchParams }: { searchParams: Promise<{ error?: string; ok?: string; articulo?: string; bodega?: string }> }) {
  const actor = await requireActor();
  if (!canManage(actor)) redirect("/");
  const query = await searchParams;
  const { warehouses, items, balances, movements, reservations } = await listInventory(actor,query.articulo,query.bodega);
  const alerts = balances.filter((balance) => Number(balance.quantity)-Number(balance.reserved) <= Number(balance.minimum_qty));
  return <>
    <div className="page-title-row"><div><div className="eyebrow">CONTROL DE EXISTENCIAS</div><h1>Inventario y bodegas</h1><p className="page-intro">Saldos, reservas y Kardex por artículo y bodega, con recepciones enlazadas a las compras.</p></div><span className="title-icon"><Boxes size={24}/></span></div>
    <Notice error={query.error} ok={query.ok}/>
    <div className="supply-summary"><div><strong>{warehouses.length}</strong><span>Bodegas</span></div><div><strong>{items.length}</strong><span>Artículos</span></div><div><strong>{alerts.length}</strong><span>Saldos bajo mínimo o agotados</span></div><Link href="/compras" className="button button-outline">Ir a compras <ArrowUpRight size={16}/></Link></div>
    <section className="section-card"><div className="section-heading"><div><div className="eyebrow">EXISTENCIAS</div><h2>Saldos disponibles por bodega</h2></div><span className="count-pill">{balances.length}</span></div>
      {balances.length ? <div className="table-wrap"><table className="data-table"><thead><tr><th>Artículo</th><th>Bodega</th><th>Físico</th><th>Reservado</th><th>Disponible</th><th>Estado</th></tr></thead><tbody>{balances.map((balance) => {
        const free = Number(balance.quantity)-Number(balance.reserved);
        return <tr key={`${balance.item_id}:${balance.warehouse_id}`}><td><strong>{balance.item_name}</strong><span className="table-sub">{balance.item_code}</span></td><td>{balance.warehouse_name}</td><td>{amount(balance.quantity)} {balance.unit}</td><td>{amount(balance.reserved)} {balance.unit}</td><td><strong>{free.toLocaleString("es-CL",{ maximumFractionDigits:3 })} {balance.unit}</strong></td><td>{free <= Number(balance.minimum_qty) ? <span className="inventory-low">Reponer · mínimo {amount(balance.minimum_qty)}</span> : <span className="inventory-good">Disponible</span>}</td></tr>;
      })}</tbody></table></div> : <p className="muted">Registre una bodega y un artículo para comenzar.</p>}
    </section>
    <div className="supply-columns">
      <section className="section-card"><div className="section-heading"><div><div className="eyebrow">MAESTROS</div><h2><Warehouse size={19}/> Bodegas</h2></div><span className="count-pill">{warehouses.length}</span></div>
        <form action={createWarehouseAction} className="form-stack compact"><div className="two-fields"><label>Código<input name="code" required minLength={2} maxLength={30} placeholder="BOD-01"/></label><label>Nombre<input name="name" required minLength={2} maxLength={120} placeholder="Bodega principal"/></label></div><SubmitButton className="button button-outline">Registrar bodega</SubmitButton></form>
        <ul className="record-list">{warehouses.map((warehouse) => <li key={warehouse.id}><strong>{warehouse.name}</strong><small>{warehouse.code}</small></li>)}</ul>
      </section>
      <section className="section-card"><div className="section-heading"><div><div className="eyebrow">CATÁLOGO</div><h2><Boxes size={19}/> Artículos</h2></div><span className="count-pill">{items.length}</span></div>
        <form action={createItemAction} className="form-stack compact"><div className="two-fields"><label>Código<input name="code" required minLength={2} maxLength={40} placeholder="REP-01"/></label><label>Unidad<select name="unit" defaultValue="un"><option value="un">Unidades</option><option value="kg">Kilogramos</option><option value="lt">Litros</option><option value="m">Metros</option><option value="m3">Metros cúbicos</option></select></label></div><label>Descripción<input name="name" required minLength={2} maxLength={160}/></label><label>Punto de reposición<input name="minimum_qty" type="number" min="0" step="0.001" defaultValue="0" required/></label><SubmitButton className="button button-outline">Registrar artículo</SubmitButton></form>
        <ul className="record-list">{items.map((item) => <li key={item.id}><strong>{item.name}</strong><small>{item.code} · mínimo {amount(item.minimum_qty)} {item.unit}</small></li>)}</ul>
      </section>
      <section className="section-card"><div className="section-heading"><div><div className="eyebrow">MOVIMIENTO</div><h2>Ajuste justificado</h2></div></div><p className="helper-text">Use un ajuste para el conteo inicial o correcciones físicas. Las compras ingresan mediante su propia recepción.</p>
        <form action={adjustStockAction} className="form-stack compact"><label>Artículo<select name="item_id" defaultValue="" required><option value="">Seleccione</option>{items.map((item) => <option key={item.id} value={item.id}>{item.code} · {item.name}</option>)}</select></label><div className="two-fields"><label>Bodega<select name="warehouse_id" defaultValue="" required><option value="">Seleccione</option>{warehouses.map((warehouse) => <option key={warehouse.id} value={warehouse.id}>{warehouse.name}</option>)}</select></label><label>Sentido<select name="direction" defaultValue="entrada"><option value="entrada">Ingreso</option><option value="salida">Salida</option></select></label></div><label>Cantidad<input name="quantity" type="number" min="0.001" step="0.001" required/></label><label>Motivo<input name="reason" minLength={5} maxLength={500} required placeholder="Inventario inicial, ajuste de conteo…"/></label><SubmitButton className="button button-outline" disabled={!items.length || !warehouses.length}>Guardar ajuste</SubmitButton></form>
      </section>
      <section className="section-card"><div className="section-heading"><div><div className="eyebrow">LOGÍSTICA INTERNA</div><h2><ArrowLeftRight size={19}/> Transferir entre bodegas</h2></div></div>
        <form action={transferStockAction} className="form-stack compact"><label>Artículo<select name="item_id" defaultValue="" required><option value="">Seleccione</option>{items.map((item) => <option key={item.id} value={item.id}>{item.code} · {item.name}</option>)}</select></label><div className="two-fields"><label>Origen<select name="from_id" defaultValue="" required><option value="">Seleccione</option>{warehouses.map((warehouse) => <option key={warehouse.id} value={warehouse.id}>{warehouse.name}</option>)}</select></label><label>Destino<select name="to_id" defaultValue="" required><option value="">Seleccione</option>{warehouses.map((warehouse) => <option key={warehouse.id} value={warehouse.id}>{warehouse.name}</option>)}</select></label></div><label>Cantidad<input name="quantity" type="number" min="0.001" step="0.001" required/></label><label>Motivo<input name="reason" minLength={5} maxLength={500} required/></label><SubmitButton className="button button-outline" disabled={!items.length || warehouses.length < 2}>Transferir stock</SubmitButton></form>
      </section>
    </div>
    <section className="section-card"><div className="section-heading"><div><div className="eyebrow">COMPROMISOS</div><h2><BookmarkCheck size={19}/> Reservas de stock</h2></div><span className="count-pill">{reservations.length}</span></div>
      <form action={reserveStockAction} className="form-grid supply-inline"><label>Artículo<select name="item_id" defaultValue="" required><option value="">Seleccione</option>{items.map((item) => <option key={item.id} value={item.id}>{item.code} · {item.name}</option>)}</select></label><label>Bodega<select name="warehouse_id" defaultValue="" required><option value="">Seleccione</option>{warehouses.map((warehouse) => <option key={warehouse.id} value={warehouse.id}>{warehouse.name}</option>)}</select></label><label>Cantidad<input name="quantity" type="number" min="0.001" step="0.001" required/></label><label>Destino o motivo<input name="reason" minLength={5} maxLength={500} required placeholder="Servicio o área que la utilizará"/></label><div className="field-full form-footer"><SubmitButton className="button button-primary" disabled={!items.length || !warehouses.length}>Reservar disponible</SubmitButton></div></form>
      {reservations.length ? <div className="table-wrap"><table className="data-table"><thead><tr><th>Artículo / bodega</th><th>Reserva</th><th>Motivo</th><th>Acciones</th></tr></thead><tbody>{reservations.map((reservation) => <tr key={reservation.id}><td><strong>{reservation.item_name}</strong><span className="table-sub">{reservation.warehouse_name}</span></td><td>{amount(reservation.quantity)} {reservation.unit}<span className="table-sub">{reservation.created_by_name} · {chileDate(reservation.created_at)}</span></td><td>{reservation.reason}</td><td><div className="reservation-actions"><form action={closeReservationAction}><input type="hidden" name="reservation_id" value={reservation.id}/><input type="hidden" name="action" value="liberar"/><SubmitButton className="button button-outline">Liberar</SubmitButton></form><form action={closeReservationAction}><input type="hidden" name="reservation_id" value={reservation.id}/><input type="hidden" name="action" value="consumir"/><SubmitButton className="button button-outline">Registrar uso</SubmitButton></form></div></td></tr>)}</tbody></table></div> : <p className="muted">Sin reservas abiertas.</p>}
    </section>
    <section className="section-card"><div className="section-heading"><div><div className="eyebrow">TRAZABILIDAD</div><h2>Kardex de movimientos</h2></div><span className="count-pill">{movements.length}</span></div>
      <form method="get" className="supply-filter"><label>Artículo<select name="articulo" defaultValue={items.some((item) => item.id === query.articulo) ? query.articulo : ""}><option value="">Todos</option>{items.map((item) => <option key={item.id} value={item.id}>{item.code} · {item.name}</option>)}</select></label><label>Bodega<select name="bodega" defaultValue={warehouses.some((warehouse) => warehouse.id === query.bodega) ? query.bodega : ""}><option value="">Todas</option>{warehouses.map((warehouse) => <option key={warehouse.id} value={warehouse.id}>{warehouse.name}</option>)}</select></label><button type="submit" className="button button-outline">Filtrar Kardex</button></form>
      {movements.length ? <div className="table-wrap"><table className="data-table"><thead><tr><th>Fecha / responsable</th><th>Artículo / bodega</th><th>Tipo</th><th>Variación física</th><th>Variación reservada</th><th>Justificación</th></tr></thead><tbody>{movements.map((movement) => <tr key={movement.id}><td>{chileDate(movement.created_at)}<span className="table-sub">{movement.actor_name}</span></td><td><strong>{movement.item_name}</strong><span className="table-sub">{movement.code} · {movement.warehouse_name}</span></td><td>{movementLabel[movement.kind] ?? movement.kind}</td><td className={Number(movement.qty_delta) < 0 ? "stock-negative" : "stock-positive"}>{Number(movement.qty_delta) > 0 ? "+" : ""}{amount(movement.qty_delta)} {movement.unit}</td><td>{Number(movement.reserved_delta) > 0 ? "+" : ""}{amount(movement.reserved_delta)} {movement.unit}</td><td>{movement.note}</td></tr>)}</tbody></table></div> : <p className="muted">No hay movimientos en este filtro.</p>}
    </section>
  </>;
}
