import Link from "next/link";
import { redirect } from "next/navigation";
import { Gauge, Wrench, CalendarClock, CircleAlert, Disc3, ArrowRight } from "lucide-react";
import { canManage, requireActor } from "@/lib/auth";
import { listMaintenance } from "@/lib/continuity";
import { createPlanAction, createTireAction, createWorkOrderAction, moveTireAction, recordReadingAction, updateAssetAction } from "@/app/continuity-actions";
import { Notice, chileDate } from "@/components/UI";
import { SubmitButton } from "@/components/Transition";

const amount=(value:number|string)=>Number(value).toLocaleString("es-CL",{maximumFractionDigits:2});
const orderStatus:Record<string,string>={abierta:"Abierta",en_trabajo:"En trabajo",cerrada:"Cerrada",cancelada:"Cancelada"};
const due=(value:Date|string|null)=>value?chileDate(`${value instanceof Date?value.toISOString().slice(0,10):String(value).slice(0,10)}T12:00:00Z`,false):"";

export default async function Maintenance({searchParams}:{searchParams:Promise<{error?:string;ok?:string}>}) {
  const actor=await requireActor();
  if (!canManage(actor)) redirect("/");
  const [{assets,plans,orders,incidents,tires},query]=await Promise.all([listMaintenance(actor),searchParams]);
  const open=orders.filter((order)=>["abierta","en_trabajo"].includes(order.status));
  return <>
    <div className="page-title-row"><div><div className="eyebrow">CONTINUIDAD OPERACIONAL</div><h1>Mantenimiento y neumáticos</h1><p className="page-intro">Lecturas de activos, planes preventivos y órdenes ligadas a averías y repuestos.</p></div><span className="title-icon"><Wrench size={23}/></span></div>
    <Notice error={query.error} ok={query.ok}/>
    <div className="supply-summary"><div><strong>{open.length}</strong><span>Órdenes abiertas</span></div><div><strong>{plans.filter((plan)=>plan.warning).length}</strong><span>Planes por vencer</span></div><div><strong>{incidents.length}</strong><span>Averías sin orden</span></div><Link className="button button-outline" href="/flota">Abrir flota <ArrowRight size={16}/></Link></div>
    <section className="section-card"><div className="section-heading"><div><div className="eyebrow">PRÓXIMAS TAREAS</div><h2><CalendarClock size={19}/> Planes preventivos</h2></div><span className="count-pill">{plans.length}</span></div>
      {plans.length?<div className="table-wrap"><table className="data-table"><thead><tr><th>Activo / pauta</th><th>Próxima ejecución</th><th>Estado</th><th>Acción</th></tr></thead><tbody>{plans.map((plan)=><tr key={plan.id}><td><strong>{plan.title}</strong><span className="table-sub">{plan.asset_code} · {plan.asset_label}</span></td><td>{plan.frequency_kind==="fecha"?due(plan.next_due_date):`${amount(plan.next_due_reading!)} ${plan.reading_unit} · actual ${amount(plan.current_reading)}`}</td><td>{plan.warning?<span className="inventory-low">Por revisar</span>:<span className="inventory-good">En plazo</span>}</td><td><form action={createWorkOrderAction}><input type="hidden" name="asset_id" value={plan.asset_id}/><input type="hidden" name="plan_id" value={plan.id}/><input type="hidden" name="incident_id" value=""/><input type="hidden" name="kind" value="preventiva"/><input type="hidden" name="title" value={plan.title}/><input type="hidden" name="description" value=""/><input type="hidden" name="scheduled_for" value=""/><SubmitButton className="button button-outline">Crear OT</SubmitButton></form></td></tr>)}</tbody></table></div>:<p className="muted">Agregue un plan para cada activo que requiere mantenciones periódicas.</p>}
    </section>
    {incidents.length>0&&<section className="section-card"><div className="section-heading"><div><div className="eyebrow">CORRECTIVOS</div><h2><CircleAlert size={19}/> Averías que requieren diagnóstico</h2></div></div>
      <div className="incident-grid">{incidents.map((incident)=><article className="incident-card" key={incident.id}><div className="incident-head"><div><strong>{incident.asset_label}</strong><span>{incident.description}</span></div></div><form action={createWorkOrderAction} className="incident-resolve"><input type="hidden" name="asset_id" value={incident.asset_id}/><input type="hidden" name="plan_id" value=""/><input type="hidden" name="incident_id" value={incident.id}/><input type="hidden" name="kind" value="correctiva"/><input type="hidden" name="title" value={`Reparar ${incident.asset_label}`}/><input type="hidden" name="description" value={incident.description}/><input type="hidden" name="scheduled_for" value=""/><input type="hidden" name="blocks_asset" value="on"/><SubmitButton className="button button-primary">Crear orden correctiva</SubmitButton></form></article>)}</div>
    </section>}
    <section className="section-card"><div className="section-heading"><div><div className="eyebrow">ÓRDENES DE TRABAJO</div><h2>Seguimiento</h2></div><span className="count-pill">{orders.length}</span></div>
      {orders.length?<div className="table-wrap"><table className="data-table"><thead><tr><th>Orden / activo</th><th>Tipo</th><th>Estado</th><th>Creada</th><th aria-label="Abrir"/></tr></thead><tbody>{orders.map((order)=><tr key={order.id}><td><Link className="table-main" href={`/mantenimiento/${order.id}`}>OT-{String(order.folio).padStart(5,"0")} · {order.title}</Link><span className="table-sub">{order.asset_code} · {order.asset_label}</span></td><td className="capitalize">{order.kind}</td><td><span className={`badge supply-status-${order.status}`}>{orderStatus[order.status]}</span></td><td>{chileDate(order.created_at)}</td><td><Link href={`/mantenimiento/${order.id}`} className="table-arrow" aria-label={`Abrir OT-${order.folio}`}><ArrowRight size={18}/></Link></td></tr>)}</tbody></table></div>:<p className="muted">Aún no se han registrado órdenes de trabajo.</p>}
    </section>
    <div className="supply-columns">
      <section className="section-card"><div className="section-heading"><div><div className="eyebrow">PLANIFICACIÓN</div><h2>Crear pauta preventiva</h2></div></div><form action={createPlanAction} className="form-stack compact"><label>Activo<select name="asset_id" defaultValue="" required><option value="">Seleccione</option>{assets.map((asset)=><option value={asset.id} key={asset.id}>{asset.code} · {asset.label}</option>)}</select></label><label>Nombre de la pauta<input name="title" required minLength={3} maxLength={160} placeholder="Cambio de aceite y filtros"/></label><label>Frecuencia<select name="frequency_kind" defaultValue="fecha"><option value="fecha">Por fecha</option><option value="lectura">Por kilometraje u horómetro</option></select></label><div className="two-fields"><label>Cada cuántos días<input name="interval_days" type="number" min="1" placeholder="Ej. 180"/></label><label>Próxima fecha<input name="next_due_date" type="date"/></label></div><div className="two-fields"><label>Cada cuántos km/horas<input name="interval_reading" type="number" min="0.01" step="0.01" placeholder="Ej. 10000"/></label><label>Próxima lectura<input name="next_due_reading" type="number" min="0" step="0.01"/></label></div><p className="helper-text">Complete los dos campos que correspondan a la frecuencia elegida. La próxima fecha o lectura se actualiza al cerrar la OT.</p><div className="two-fields"><label>Alerta previa (días)<input name="lead_days" type="number" min="0" max="365" defaultValue="15" required/></label><label>Alerta previa (km/horas)<input name="lead_reading" type="number" min="0" step="0.01" defaultValue="500" required/></label></div><SubmitButton className="button button-outline" disabled={!assets.length}>Guardar pauta</SubmitButton></form></section>
      <section className="section-card"><div className="section-heading"><div><div className="eyebrow">TRABAJO NO PROGRAMADO</div><h2>Crear orden manual</h2></div></div><form action={createWorkOrderAction} className="form-stack compact"><input type="hidden" name="plan_id" value=""/><input type="hidden" name="incident_id" value=""/><label>Activo<select name="asset_id" defaultValue="" required><option value="">Seleccione</option>{assets.map((asset)=><option value={asset.id} key={asset.id}>{asset.code} · {asset.label}</option>)}</select></label><div className="two-fields"><label>Tipo<select name="kind" defaultValue="correctiva"><option value="correctiva">Correctiva</option><option value="preventiva">Preventiva puntual</option><option value="neumaticos">Neumáticos</option></select></label><label>Fecha programada<input name="scheduled_for" type="date"/></label></div><label>Trabajo requerido<input name="title" required minLength={3} maxLength={160}/></label><label>Descripción<textarea name="description" maxLength={1500} rows={3}/></label><label className="check-row"><input type="checkbox" name="blocks_asset"/> Inmovilizar activo al iniciar</label><SubmitButton className="button button-outline" disabled={!assets.length}>Crear orden</SubmitButton></form></section>
      <section className="section-card"><div className="section-heading"><div><div className="eyebrow">FICHA TÉCNICA</div><h2>Actualizar activo</h2></div></div><form action={updateAssetAction} className="form-stack compact"><label>Activo<select name="asset_id" defaultValue="" required><option value="">Seleccione</option>{assets.map((asset)=><option value={asset.id} key={asset.id}>{asset.code} · {asset.label}</option>)}</select></label><div className="two-fields"><label>Marca<input name="brand" maxLength={90}/></label><label>Modelo<input name="model" maxLength={90}/></label></div><div className="two-fields"><label>Año<input name="model_year" type="number" min="1950" max="2100"/></label><label>Unidad de lectura<select name="reading_unit" defaultValue="km"><option value="km">Kilómetros</option><option value="horas">Horas</option><option value="sin">Sin lectura</option></select></label></div><p className="helper-text">La unidad no puede cambiarse una vez que el activo tenga lecturas.</p><SubmitButton className="button button-outline" disabled={!assets.length}>Actualizar ficha</SubmitButton></form></section>
      <section className="section-card"><div className="section-heading"><div><div className="eyebrow">ODÓMETRO Y HORÓMETRO</div><h2><Gauge size={19}/> Registrar lectura</h2></div></div><form action={recordReadingAction} className="form-stack compact"><label>Activo<select name="asset_id" defaultValue="" required><option value="">Seleccione</option>{assets.map((asset)=><option value={asset.id} key={asset.id}>{asset.code} · {asset.label} · {amount(asset.current_reading)} {asset.reading_unit}</option>)}</select></label><label>Nueva lectura<input name="reading" type="number" min="0" step="0.01" required/></label><label>Origen o justificación<input name="note" required minLength={5} maxLength={500}/></label><SubmitButton className="button button-outline" disabled={!assets.length}>Guardar lectura</SubmitButton></form></section>
    </div>
    <section className="section-card"><div className="section-heading"><div><div className="eyebrow">NEUMÁTICOS</div><h2><Disc3 size={19}/> Posiciones e historial</h2></div><span className="count-pill">{tires.length}</span></div>
      <form action={createTireAction} className="form-grid supply-inline"><label>Código único<input name="code" required minLength={2} maxLength={45}/></label><label>Marca<input name="brand" maxLength={90}/></label><label>Medida<input name="size" maxLength={60} placeholder="Ej. 11R22.5"/></label><div className="field-full form-footer"><SubmitButton className="button button-outline">Registrar neumático</SubmitButton></div></form>
      {tires.length?<div className="table-wrap"><table className="data-table"><thead><tr><th>Código / medida</th><th>Estado</th><th>Activo y posición</th><th>Movimiento</th></tr></thead><tbody>{tires.map((tire)=><tr key={tire.id}><td><strong>{tire.code}</strong><span className="table-sub">{tire.brand??""} {tire.size??""}</span></td><td className="capitalize">{tire.status}</td><td>{tire.asset_label??"Sin instalar"}<span className="table-sub">{tire.position??""}</span></td><td><form action={moveTireAction} className="tire-move"><input type="hidden" name="tire_id" value={tire.id}/><select name="action" defaultValue={tire.status==="instalado"?"retirar":"instalar"}><option value="instalar">Instalar / rotar</option><option value="retirar">Retirar</option></select><select name="asset_id" defaultValue=""><option value="">Activo (al instalar)</option>{assets.map((asset)=><option key={asset.id} value={asset.id}>{asset.code} · {asset.label}</option>)}</select><input name="position" maxLength={35} placeholder="Posición"/><input name="reason" minLength={5} maxLength={500} required placeholder="Motivo del movimiento"/><SubmitButton className="button button-outline">Guardar</SubmitButton></form></td></tr>)}</tbody></table></div>:<p className="muted">Registre los neumáticos para iniciar el historial de posiciones.</p>}
    </section>
  </>;
}
